import { CheckCircle2, ChevronRight, CircleX, CreditCard, MapPin, Minus, Plus, ShieldCheck, ShoppingBag, Trash2, Truck } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { ConfirmButton, InlineNotice } from '../../components/common/UI'
import { SafeImage } from '../../components/common/SafeImage'
import { useApp } from '../../store/AppStore'
import { createOrder, getCart, payOrder, type ApiCartItem } from '../../services/commerce'

export function CartPage(){
 const {cart,userLoading,updateCart,removeCart}=useApp();const total=cart.filter(x=>x.selected&&x.sellable).reduce((sum,x)=>sum+Number(x.subtotal),0)
 return <div className="page"><div className="container"><div className="page-head"><div><h1>购物车</h1><p>{userLoading?'正在同步当前用户购物车…':'购物车数据来自当前登录用户的后端账户。'}</p></div><Link to="/products" className="btn ghost">继续购物 <ChevronRight/></Link></div><div className="cart-layout"><section className="cart-list card">{cart.map(x=><div className={`cart-line ${!x.sellable?'invalid':''}`} key={x.id}><input type="checkbox" checked={x.selected} readOnly/><SafeImage src={x.image_url||''} alt={x.product_name}/><div><h3>{x.product_name}</h3><p>{x.spec_name}</p>{!x.sellable&&<span className="status-pill danger">库存不足或商品失效</span>}</div><span className="unit-price">¥{x.unit_price}</span><div className="quantity"><button onClick={()=>void updateCart(x.id,Math.max(1,x.quantity-1))}><Minus size={13}/></button><input value={x.quantity} readOnly/><button onClick={()=>void updateCart(x.id,x.quantity+1)}><Plus size={13}/></button></div><strong className="line-total">¥{Number(x.subtotal).toFixed(2)}</strong><ConfirmButton className="icon-btn" confirmText="确定删除这件商品？" onConfirm={()=>void removeCart(x.id)}><Trash2 size={16}/></ConfirmButton></div>)}</section><aside className="summary-box card"><h2>订单小计</h2><div className="price-line"><span>商品数量</span><span>{cart.reduce((sum,x)=>sum+x.quantity,0)} 件</span></div><div className="price-line total"><strong>合计</strong><strong>¥{total.toFixed(2)}</strong></div><Link className="btn primary large" to={total>0?'/checkout':'/cart'}>去结算</Link><p style={{fontSize:11,textAlign:'center'}}><ShieldCheck size={13}/> 支付接口仅为模拟支付</p></aside></div></div></div>
}
export function CheckoutPage(){
 const nav=useNavigate();const {notify}=useApp();const [items,setItems]=useState<ApiCartItem[]>([]);const [remark,setRemark]=useState('');const [pay,setPay]=useState('MOCK_BALANCE');const total=useMemo(()=>items.reduce((s,x)=>s+Number(x.subtotal),0),[items])
 useEffect(()=>{getCart().then(x=>setItems(x.items.filter(v=>v.selected&&v.sellable))).catch(()=>notify('请登录并确保后端可用后结算','error'))},[])
 const submit=async()=>{try{const order=await createOrder(items.map(x=>x.id),{name:'林小满',phone:'13800000000',address:'上海市徐汇区虹桥路 718 号 2 栋 1206'},remark);const paid=await payOrder(order.id,pay);nav(`/order-result?status=success&order=${paid.order_no}&amount=${paid.paid_amount}`)}catch(e){notify(e instanceof Error?e.message:'订单创建失败','error')}}
 return <div className="page"><div className="container"><div className="page-head"><div><h1>确认订单</h1><p>提交时将在一个事务内检查并扣减库存、保存商品快照。</p></div></div><div className="checkout-layout"><main className="checkout-main"><section className="checkout-section card"><h2><MapPin size={18}/> 收货地址</h2><div className="address-card selected"><span><b>林小满 · 138****0000</b><p>上海市徐汇区虹桥路 718 号 2 栋 1206</p></span><CheckCircle2 color="var(--sage)"/></div></section><section className="checkout-section card"><h2><ShoppingBag size={18}/> 商品清单</h2>{items.map(x=><div className="cart-line" style={{gridTemplateColumns:'70px 1fr 80px 90px'}} key={x.id}><SafeImage src={x.image_url||''}/><span><b>{x.product_name}</b><small style={{display:'block'}}>{x.spec_name}</small></span><span>× {x.quantity}</span><strong>¥{Number(x.subtotal).toFixed(2)}</strong></div>)}</section><section className="checkout-section card"><h2><Truck size={18}/> 配送方式</h2><button className="pay-option active">标准配送</button></section><section className="checkout-section card"><h2>订单备注</h2><textarea className="textarea" value={remark} onChange={e=>setRemark(e.target.value)} maxLength={500}/></section><section className="checkout-section card"><h2><CreditCard size={18}/> 模拟支付方式</h2><div className="pay-options">{[['MOCK_BALANCE','余额模拟支付'],['MOCK_ALIPAY','支付宝（演示）'],['MOCK_WECHAT','微信支付（演示）']].map(([v,l])=><button key={v} className={`pay-option ${pay===v?'active':''}`} onClick={()=>setPay(v)}>{l}</button>)}</div><InlineNotice tone="info" title="模拟支付">不会调用真实支付渠道，也不会产生真实扣款。</InlineNotice></section></main><aside className="summary-box card"><h2>费用明细</h2><div className="price-line"><span>商品金额</span><span>¥{total.toFixed(2)}</span></div><div className="price-line"><span>运费</span><span>{total>=59?'¥0.00':'¥6.00'}</span></div><div className="price-line total"><strong>应付金额</strong><strong>¥{(total+(total>=59?0:6)).toFixed(2)}</strong></div><button className="btn primary large" disabled={!items.length} onClick={submit}>提交订单并模拟支付</button></aside></div></div></div>
}

export function OrderResultPage(){const [params]=useSearchParams();const success=params.get('status')!=='failed';return <div className="page"><div className="container" style={{maxWidth:760}}><div className="card empty-state" style={{padding:'80px 30px'}}>{success?<CheckCircle2 size={70} color="var(--sage)"/>:<CircleX size={70} color="var(--red)"/>}<h1>{success?'支付成功':'支付失败'}</h1><p>{success?'模拟支付记录已保存，订单状态已更新为已支付。':'订单仍为待支付，可稍后重试。'}</p><div className="soft-card" style={{padding:18}}><div className="price-line"><span>订单编号</span><b>{params.get('order')||'—'}</b></div><div className="price-line"><span>订单金额</span><b>¥{params.get('amount')||'0.00'}</b></div></div><div style={{display:'flex',gap:10}}><Link className="btn ghost" to="/account?tab=orders">查看订单</Link><Link className="btn primary" to="/products">继续购物</Link></div></div></div></div>}
