// @ts-nocheck -- Cytoscape's stylesheet generics reject valid numeric runtime values.
import cytoscape from 'cytoscape'
import { Crosshair, GitFork, Info, Maximize2, Minus, Plus, RotateCcw, Search } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getProductGraph, resolveProductCode, type ProductGraphData } from '../../services/api'

export function GraphPage(){
 const {id}=useParams();const productCode=resolveProductCode(id);const ref=useRef<HTMLDivElement>(null);const cyRef=useRef<cytoscape.Core|null>(null);const [graph,setGraph]=useState<ProductGraphData|null>(null);const [selected,setSelected]=useState<any>(null);const [highlight,setHighlight]=useState(false);
 useEffect(()=>{let active=true;getProductGraph(id).then(data=>{if(active){setGraph(data);setSelected(data.nodes[0]?.data||null)}});return()=>{active=false}},[id]);
 useEffect(()=>{if(!ref.current||!graph)return;const cy=cytoscape({container:ref.current,elements:[...graph.nodes,...graph.edges],layout:{name:'cose',animate:false,padding:40},style:[{selector:'node',style:{'background-color':'#dfe8d9','label':'data(label)','color':'#394238','font-size':11,'text-valign':'center','text-halign':'center','width':54,'height':54,'border-width':2,'border-color':'#fff','text-wrap':'wrap','text-max-width':75}},{selector:'node[type="foodproduct"],node[type="product"]',style:{'background-color':'#526648','color':'#fff','width':92,'height':92,'font-size':12}},{selector:'node[type="risktag"],node[type="risk"]',style:{'background-color':'#e7b99f'}},{selector:'node[type="nutrient"],node[type="nutrition"]',style:{'background-color':'#e9d8a8'}},{selector:'node[type="brand"],node[type="category"]',style:{'background-color':'#d9d8e8'}},{selector:'edge',style:{'width':1.5,'line-color':'#b8c0b3','target-arrow-color':'#b8c0b3','target-arrow-shape':'triangle','curve-style':'bezier','label':'data(label)','font-size':8,'color':'#788076','text-background-color':'#f1f2ec','text-background-opacity':.8,'text-background-padding':2}},{selector:'.highlighted',style:{'background-color':'#c87945','line-color':'#c87945','target-arrow-color':'#c87945','width':4}}]});cy.on('tap','node',e=>setSelected(e.target.data()));cyRef.current=cy;return()=>{cy.destroy();cyRef.current=null}},[graph]);
 const zoom=(delta:number)=>cyRef.current?.zoom({level:(cyRef.current.zoom()||1)+delta,renderedPosition:{x:(ref.current?.clientWidth||0)/2,y:(ref.current?.clientHeight||0)/2}});
 const path=()=>{const cy=cyRef.current;if(!cy)return;cy.elements().removeClass('highlighted');if(!highlight){const risks=cy.nodes('[type="risktag"], [type="risk"]');risks.forEach(risk=>{risk.addClass('highlighted');risk.connectedEdges().addClass('highlighted');risk.predecessors().addClass('highlighted')})}setHighlight(!highlight)};
 return <div className="graph-page"><aside className="graph-side"><Link to={`/product/${productCode}`} className="btn ghost" style={{marginBottom:18}}>← 返回商品详情</Link><h3>图谱图例</h3><p style={{fontSize:12}}>拖动节点整理视图；滚轮或按钮可缩放。{graph?.source==='mock'?' 当前为本地降级数据。':''}</p><div className="legend"><span><i style={{background:'#526648'}}/>当前商品</span><span><i style={{background:'#dfe8d9'}}/>成分 / 添加剂</span><span><i style={{background:'#e7b99f'}}/>风险标签</span><span><i style={{background:'#e9d8a8'}}/>营养指标</span><span><i style={{background:'#d9d8e8'}}/>品牌 / 分类</span></div><div className="divider"/><h3>关系说明</h3>{['包含：商品标签明确列出的成分','可能含有：来自包装交叉接触提示','关联风险：成分到风险标签的审核关系','品牌 / 分类：商品的基础归属'].map(x=><div className="relationship" key={x}>{x}</div>)}</aside><main className="graph-canvas-wrap"><div ref={ref} className="graph-canvas"/><div className="graph-toolbar"><div className="tools"><button className="icon-btn" onClick={()=>zoom(.2)} title="放大"><Plus/></button><button className="icon-btn" onClick={()=>zoom(-.2)} title="缩小"><Minus/></button><button className="icon-btn" onClick={()=>cyRef.current?.fit(undefined,40)} title="重置视图"><RotateCcw/></button><button className="icon-btn" onClick={()=>cyRef.current?.center()} title="居中"><Crosshair/></button><button className="icon-btn" onClick={()=>cyRef.current?.fit(undefined,10)} title="适应画布"><Maximize2/></button></div><button className={`btn ${highlight?'primary':'outline'}`} onClick={path}><GitFork size={16}/>高亮风险路径</button></div></main><aside className="graph-side right"><h3>节点详情</h3><div className="node-detail"><small>{selected?.type||'加载中'}</small><h2>{selected?.label||'正在读取图谱'}</h2><p>{selected?.business_code||'平台标准知识实体'}</p></div><div className="divider"/><h3>数据状态</h3><p style={{fontSize:12}}>商品编码：{productCode}<br/>明确含有：{graph?.summary?.contains_count??'—'}<br/>可能含有：{graph?.summary?.may_contain_count??'—'}<br/>风险标签：{graph?.summary?.risk_count??'—'}</p><span className="status-pill success">{graph?.summary?.information_status||'LOADING'}</span><div className="notice info" style={{marginTop:20}}><Info size={17}/><div><strong>{graph?.source==='api'?'图谱服务数据':'图谱降级模式'}</strong><p>图谱不可用不代表商品安全，仍需查看商品原始标签。</p></div></div><div className="field"><label>查找节点</label><div className="nav-search" style={{maxWidth:'none'}}><Search/><input placeholder="输入成分名称"/></div></div></aside></div>
}