import { ArrowRight, BookOpen, CheckCircle2, GitFork, Search, ShieldCheck, Sparkles } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ProductCard } from '../../components/product/ProductCard'
import { SafeImage } from '../../components/common/SafeImage'
import { SectionTitle } from '../../components/common/UI'
import { categories, products } from '../../mock/data'

export function HomePage(){
  const [query,setQuery]=useState('帮我找不含花生及花生制品、50元以内的早餐麦片'); const navigate=useNavigate(); const go=()=>navigate(`/smart-filter?q=${encodeURIComponent(query)}`)
  return <><section className="hero"><div className="hero-inner"><div className="hero-copy"><span className="eyebrow">KNOW WHAT YOU EAT · 知其然，也知其所以然</span><h1>告诉 AI 你想吃什么，需要避开什么</h1><p>用自然语言说出需求，知识图谱会核对商品标签、成分别名与风险关系，为你找到有证据的选择。</p><div className="hero-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()}/><button className="btn primary large" onClick={go}><Sparkles size={18}/>智能筛选</button></div><div className="quick-tags">{['不含花生','低糖早餐','高蛋白','配料简单','50元以内'].map(x=><button key={x} onClick={()=>setQuery(`帮我找${x}的食品`)}>{x}</button>)}</div><div className="trust-row"><span><CheckCircle2 size={16}/>规则先判断</span><span><GitFork size={16}/>证据可追溯</span><span><ShieldCheck size={16}/>不确定性明确提示</span></div></div><div className="hero-visual"><SafeImage className="main-img" src="https://images.unsplash.com/photo-1490818387583-1baba5e638af?auto=format&fit=crop&w=1200&q=85" alt="健康早餐桌面"/><div className="float-card one"><strong><span className="dot"/>完全匹配</strong>未检出花生及其衍生物</div><div className="float-card two"><strong>证据来自商品标签</strong>最近审核 · 2026-07-16</div></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="SHOP BY CATEGORY" title="按你的日常节奏，找到合适的一餐" desc="从早餐到零食，所有商品都带有结构化成分信息。" action={<Link to="/products" className="btn ghost">查看全部 <ArrowRight size={16}/></Link>}/><div className="category-grid">{categories.map(c=><Link key={c.name} to={`/products?category=${c.name}`} className="category-card"><span className="emoji">{c.icon}</span><span><b>{c.name}</b><small>{c.count} 件商品</small></span></Link>)}</div></div></section>
  <section className="section alt"><div className="container"><SectionTitle eyebrow="CURATED FOR YOU" title="热卖，也更懂配料" desc="综合销量、标签完整度与近期偏好，为你精选。"/><div className="product-grid">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
  <section className="section"><div className="container"><div className="feature-strip"><div className="feature-large soft-card"><span className="eyebrow">偏好推荐</span><h2>排除花生，优先低糖与简单配料</h2><p>你的默认策略已命中 14 件商品，其中 8 件为完全匹配。</p><Link className="btn primary" to="/account/preferences">管理我的成分偏好 <ArrowRight size={16}/></Link></div><Link to="/smart-filter?q=适合儿童早餐的低糖食品" className="feature-small orange soft-card"><span className="eyebrow">热门筛选</span><h3>儿童早餐怎么选？</h3><p>低糖、配料简单、明确过敏原</p></Link><Link to="/smart-filter?q=高蛋白无添加糖植物饮" className="feature-small green soft-card"><span className="eyebrow">本周上升</span><h3>植物蛋白轻负担</h3><p>高蛋白、无添加糖、低脂</p></Link></div></div></section>
  <section className="section alt"><div className="container"><SectionTitle eyebrow="INGREDIENT NOTES" title="今天，认识三个常见成分" desc="读懂标签，不必成为食品工程师。"/><div className="knowledge-grid"><article className="knowledge-card card"><div className="icon-circle">🌾</div><h3>菊粉是什么？</h3><p>一种常见膳食纤维来源，也可能以“菊苣纤维”出现在配料表中。点击可查看别名与关联商品。</p><Link to="/graph/1" className="text-button">查看图谱关系 →</Link></article><article className="knowledge-card card"><div className="icon-circle">🥜</div><h3>“可能含有”不等于“不含”</h3><p>通常表示生产线存在交叉接触可能。若设为排除成分，平台会标记为“存在风险”。</p><Link to="/smart-filter" className="text-button">按风险筛选 →</Link></article><article className="knowledge-card card"><div className="icon-circle"><BookOpen size={22}/></div><h3>证据从哪里来？</h3><p>商品包装标签、商家提交资料与人工审核记录共同构成可追溯的信息来源。</p><Link to="/product/1" className="text-button">查看示例商品 →</Link></article></div></div></section>
  <section className="section"><div className="container"><SectionTitle eyebrow="RECENTLY VIEWED" title="最近浏览" action={<Link to="/account?tab=history" className="text-button">查看全部</Link>}/><div className="product-grid">{products.slice(12,16).map(p=><ProductCard key={p.id} product={p} compact/>)}</div></div></section></>
}
