import { Eye, EyeOff, Leaf, LockKeyhole, Phone } from 'lucide-react'
import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { SafeImage } from '../../components/common/SafeImage'
import { useApp } from '../../store/AppStore'

export function LoginPage() {
  const [mode,setMode]=useState<'login'|'register'>('login'); const [show,setShow]=useState(false); const [form,setForm]=useState({account:'13800138000',password:'demo1234',confirm:'',agree:true}); const [errors,setErrors]=useState<Record<string,string>>({}); const {login,notify}=useApp(); const navigate=useNavigate()
  const submit=(e:React.FormEvent)=>{e.preventDefault(); const next:Record<string,string>={}; if(!/^1\d{10}$/.test(form.account)&&form.account.length<4)next.account='请输入有效手机号或不少于4位的账号'; if(form.password.length<6)next.password='密码至少需要6位'; if(mode==='register'&&form.confirm!==form.password)next.confirm='两次输入的密码不一致'; if(!form.agree)next.agree='请先阅读并同意用户协议'; setErrors(next); if(Object.keys(next).length===0){login();notify(mode==='login'?'登录成功，正在进入首页':'注册成功，已自动登录');navigate('/')}}
  return <div className="auth-page"><section className="auth-visual"><SafeImage src="https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1600&q=85" alt="自然食材"/><Link to="/" className="auth-brand"><span className="logo-mark">知</span></Link><div className="auth-quote"><h2>看懂配料，安心选择每一口。</h2><p>知识图谱连接成分别名、衍生关系与商品证据，让复杂标签变得清楚。</p></div></section><section className="auth-form-side"><div className="auth-box"><Link to="/" className="logo"><span className="logo-mark">知</span><span><b>知味集</b><small>FoodGraph Market</small></span></Link><h1>{mode==='login'?'欢迎回来':'创建你的知味账户'}</h1><p>{mode==='login'?'继续探索更适合你的食品。':'保存成分偏好，获得可追溯的个性化筛选。'}</p><div className="auth-tabs"><button className={mode==='login'?'active':''} onClick={()=>setMode('login')}>登录</button><button className={mode==='register'?'active':''} onClick={()=>setMode('register')}>注册</button></div><form className="auth-form" onSubmit={submit}><div className="field"><label><Phone size={14}/> 手机号或账号</label><input className="input" value={form.account} onChange={e=>setForm({...form,account:e.target.value})} placeholder="请输入手机号或账号"/>{errors.account&&<span className="error">{errors.account}</span>}</div><div className="field"><label><LockKeyhole size={14}/> 密码</label><div className="password-wrap"><input className="input" type={show?'text':'password'} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="至少6位密码"/><button type="button" className="icon-btn" onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div>{errors.password&&<span className="error">{errors.password}</span>}</div>{mode==='register'&&<div className="field"><label>确认密码</label><input className="input" type="password" value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})} placeholder="请再次输入密码"/>{errors.confirm&&<span className="error">{errors.confirm}</span>}</div>}<div className="auth-extra"><label className="checkbox"><input type="checkbox" checked={form.agree} onChange={e=>setForm({...form,agree:e.target.checked})}/>我已阅读并同意用户协议和隐私政策</label>{mode==='login'&&<a onClick={()=>notify('已发送模拟重置指引','info')}>忘记密码？</a>}</div>{errors.agree&&<span className="field error">{errors.agree}</span>}<button className="btn primary large" type="submit">{mode==='login'?'登录':'注册并登录'}</button><div className="notice info"><Leaf size={18}/><div><strong>偏好隐私说明</strong><p>成分偏好仅用于筛选和排序，不用于推断疾病或诊疗需求。</p></div></div></form></div></section></div>
}
