import { Filter, Grid2X2, List, Search } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Modal } from '../../components/common/UI'
import { ProductCard } from '../../components/product/ProductCard'
import { ProductFilterPanel } from '../../components/product/ProductFilterPanel'
import { getProductBrands,getProductCategoryCounts,queryProducts,type BrandOption,type CategoryCount,type ProductQuery } from '../../services/productCatalog'
import type { Product } from '../../types'

const numberValue=(params:URLSearchParams,key:string)=>{const value=params.get(key);return value===null||value===''?undefined:Number(value)}
export function ProductsPage(){
 const [params,setParams]=useSearchParams();const [items,setItems]=useState<Product[]>([]);const [total,setTotal]=useState(0);const [categories,setCategories]=useState<CategoryCount[]>([]);const [brands,setBrands]=useState<BrandOption[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [drawer,setDrawer]=useState(false);const [view,setView]=useState<'grid'|'list'>('grid');const pageSize=12
 const query=useMemo<ProductQuery>(()=>({keyword:params.get('keyword')||params.get('q')||undefined,category:params.get('category')||undefined,brand:params.get('brand')||undefined,excludedIngredients:params.getAll('exclude'),sugarMax:numberValue(params,'sugar_max'),fatMax:numberValue(params,'fat_max'),proteinMin:numberValue(params,'protein_min'),sodiumMax:numberValue(params,'sodium_max'),priceMin:numberValue(params,'price_min'),priceMax:numberValue(params,'price_max'),page:Number(params.get('page')||1),pageSize,sortBy:(params.get('sort_by') as ProductQuery['sortBy'])||'created_at',sortOrder:(params.get('sort_order') as ProductQuery['sortOrder'])||'desc'}),[params])
 useEffect(()=>{Promise.all([getProductCategoryCounts(),getProductBrands()]).then(([c,b])=>{setCategories(c);setBrands(b)}).catch(e=>setError(e instanceof Error?e.message:'筛选选项加载失败'))},[])
 useEffect(()=>{let active=true;setLoading(true);queryProducts(query).then(result=>{if(active){setItems(result.items);setTotal(result.total);setError('')}}).catch(e=>{if(active){setItems([]);setTotal(0);setError(e instanceof Error?e.message:'商品加载失败')}}).finally(()=>active&&setLoading(false));return()=>{active=false}},[query])
 const update=(patch:Record<string,string|string[]|number|undefined>)=>{const next=new URLSearchParams(params);for(const [key,value] of Object.entries(patch)){next.delete(key);if(Array.isArray(value))value.forEach(item=>next.append(key,item));else if(value!==undefined&&value!=='')next.set(key,String(value))}if(!('page' in patch))next.set('page','1');next.delete('q');setParams(next)}
 const filterValue={category:query.category,brand:query.brand,excludedIngredients:query.excludedIngredients,sugarMax:query.sugarMax,fatMax:query.fatMax,proteinMin:query.proteinMin,sodiumMax:query.sodiumMax,priceMin:query.priceMin,priceMax:query.priceMax}
 const changeFilters=(patch:Partial<typeof filterValue>)=>{const mapped:Record<string,string|string[]|number|undefined>={};if('category' in patch)mapped.category=patch.category;if('brand' in patch)mapped.brand=patch.brand;if('excludedIngredients' in patch)mapped.exclude=patch.excludedIngredients;if('sugarMax' in patch)mapped.sugar_max=patch.sugarMax;if('fatMax' in patch)mapped.fat_max=patch.fatMax;if('proteinMin' in patch)mapped.protein_min=patch.proteinMin;if('sodiumMax' in patch)mapped.sodium_max=patch.sodiumMax;if('priceMin' in patch)mapped.price_min=patch.priceMin;if('priceMax' in patch)mapped.price_max=patch.priceMax;update(mapped)}
 const reset=()=>setParams(new URLSearchParams())
 const pages=Math.max(1,Math.ceil(total/pageSize))
 return <div className="page filter-scroll-page product-filter-page"><div className="container"><div className="breadcrumbs"><span>首页</span><span>/</span><span>商品列表</span></div><div className="page-head"><div><h1>{query.keyword?`“${query.keyword}” 的搜索结果`:'全部食品'}</h1><p>共找到 {total} 件商品 · 数据来自商品数据库</p></div><button className="btn outline filter-drawer-button" onClick={()=>setDrawer(true)}><Filter size={17}/>筛选</button></div>{error&&<div className="notice error">{error}</div>}<div className="catalog-layout"><aside className="filter-panel card"><ProductFilterPanel value={filterValue} categories={categories} brands={brands} onChange={changeFilters} onReset={reset}/></aside><section className="catalog-results-scroll"><div className="toolbar card"><div className="toolbar-left"><div className="nav-search"><Search/><input value={query.keyword||''} onChange={e=>update({keyword:e.target.value||undefined})} placeholder="搜索名称或商品编码"/></div><strong>{loading?'加载中…':`${total} 件商品`}</strong></div><div className="toolbar-right"><select className="select" value={`${query.sortBy}:${query.sortOrder}`} onChange={e=>{const [sort_by,sort_order]=e.target.value.split(':');update({sort_by,sort_order})}}><option value="created_at:desc">综合排序</option><option value="price:asc">价格从低到高</option><option value="price:desc">价格从高到低</option><option value="name:asc">名称排序</option></select><div className="view-switch"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')}><Grid2X2 size={17}/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={17}/></button></div></div></div>{items.length?<><div className={`product-grid catalog-products ${view}`}>{items.map(item=><ProductCard key={item.productCode} product={item}/>)}</div><div className="pagination"><button disabled={query.page===1} onClick={()=>update({page:Math.max(1,query.page-1)})}>‹</button><button className="active">{query.page}</button><button disabled={query.page===pages} onClick={()=>update({page:Math.min(pages,query.page+1)})}>›</button></div></>:<div className="card empty-state"><div className="empty-illustration">⌕</div><h3>{loading?'正在加载商品':'没有找到符合条件的商品'}</h3><p>可移除部分排除成分或放宽价格、营养条件。</p><button className="btn primary" onClick={reset}>清空筛选</button></div>}</section></div><Modal open={drawer} title="筛选商品" onClose={()=>setDrawer(false)} footer={<><button className="btn ghost" onClick={reset}>重置</button><button className="btn primary" onClick={()=>setDrawer(false)}>查看 {total} 件商品</button></>}><ProductFilterPanel value={filterValue} categories={categories} brands={brands} onChange={changeFilters} onReset={reset}/></Modal></div></div>
}
