import { Filter, Grid2X2, List, RotateCcw, Search } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Modal } from '../../components/common/UI'
import { ProductCard } from '../../components/product/ProductCard'
import { brands, categories } from '../../mock/data'
import { getProducts } from '../../services/api'
import type { Product } from '../../types'

function Filters({category,setCategory,brand,setBrand,maxPrice,setMaxPrice}:{category:string;setCategory:(v:string)=>void;brand:string;setBrand:(v:string)=>void;maxPrice:number;setMaxPrice:(v:number)=>void}){return <><div className="filter-group"><h4>商品分类</h4><div className="check-list"><label><input type="radio" checked={!category} onChange={()=>setCategory('')}/>全部分类</label>{categories.slice(0,8).map(c=><label key={c.name}><input type="radio" checked={category===c.name} onChange={()=>setCategory(c.name)}/>{c.name}<span className="filter-count">{c.count}</span></label>)}</div></div><div className="filter-group"><h4>品牌</h4><select className="select" value={brand} onChange={e=>setBrand(e.target.value)}><option value="">全部品牌</option>{brands.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter-group"><h4>价格区间</h4><input type="range" min="10" max="100" value={maxPrice} onChange={e=>setMaxPrice(+e.target.value)} style={{width:'100%',accentColor:'var(--sage)'}}/><div className="range-row"><input className="input" value="¥0" readOnly/><span>—</span><input className="input" value={`¥${maxPrice}`} readOnly/></div></div><div className="filter-group"><h4>排除成分</h4><input className="input" placeholder="搜索并排除成分"/><div className="tag-row" style={{marginTop:8}}><span>花生 ×</span><span>花生酱 ×</span></div></div><div className="filter-group"><h4>偏好成分</h4><div className="check-list"><label><input type="checkbox"/>全谷物</label><label><input type="checkbox"/>高蛋白</label><label><input type="checkbox"/>膳食纤维</label></div></div><div className="filter-group"><h4>营养范围（每100g/mL）</h4><div className="check-list"><label><input type="checkbox"/>糖 ≤ 5g</label><label><input type="checkbox"/>脂肪 ≤ 10g</label><label><input type="checkbox"/>蛋白质 ≥ 8g</label><label><input type="checkbox"/>钠 ≤ 500mg</label></div></div><div className="filter-group"><h4>食品添加剂</h4><div className="check-list"><label><input type="radio" name="add"/>不限</label><label><input type="radio" name="add"/>不含添加剂</label><label><input type="radio" name="add"/>仅常见添加剂</label></div></div></>}

export function ProductsPage(){
 const [params]=useSearchParams();
 const [query,setQuery]=useState(params.get('q')||'');
 const [category,setCategory]=useState(params.get('category')||'');
 const [brand,setBrand]=useState('');
 const [maxPrice,setMaxPrice]=useState(100);
 const [view,setView]=useState<'grid'|'list'>('grid');
 const [sort,setSort]=useState('综合排序');
 const [drawer,setDrawer]=useState(false);
 const [page,setPage]=useState(1);
 const [total,setTotal]=useState(0);
 const [items,setItems]=useState<Product[]>([]);
 const [source,setSource]=useState<'api'|'mock'>('api');
 const [loading,setLoading]=useState(true);
 const pageSize=12;
 useEffect(()=>{let active=true;setLoading(true);const apiParams=new URLSearchParams({page:String(page),page_size:String(pageSize),sort_by:sort==='价格从低到高'?'price':'created_at',sort_order:sort==='价格从低到高'?'asc':'desc'});if(query)apiParams.set('keyword',query);getProducts(apiParams).then(result=>{if(active){setItems(result.items);setTotal(result.total);setSource(result.source)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[page,query,sort]);
 const visible=useMemo(()=>items.filter(p=>(!category||p.category===category)&&(!brand||p.brand===brand)&&p.price<=maxPrice),[items,category,brand,maxPrice]);
 const pages=Math.max(1,Math.ceil(total/pageSize));
 const reset=()=>{setCategory('');setBrand('');setMaxPrice(100);setQuery('');setPage(1)};
 return <div className="page"><div className="container"><div className="breadcrumbs"><span>首页</span><span>/</span><span>商品列表</span></div><div className="page-head"><div><h1>{query?`“${query}” 的搜索结果`:'全部食品'}</h1><p>共找到 {total} 件商品 · {source==='api'?'实时API数据':'API暂不可用，当前展示本地数据'}</p></div><button className="btn outline filter-drawer-button" onClick={()=>setDrawer(true)}><Filter size={17}/>筛选</button></div><div className="catalog-layout"><aside className="filter-panel card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3>筛选条件</h3><button className="icon-btn" onClick={reset}><RotateCcw size={16}/></button></div><Filters {...{category,setCategory,brand,setBrand,maxPrice,setMaxPrice}}/></aside><section><div className="toolbar card"><div className="toolbar-left"><div className="nav-search"><Search/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="在结果中搜索"/></div><strong>{loading?'加载中…':`${visible.length} 件商品`}</strong></div><div className="toolbar-right"><select className="select" value={sort} onChange={e=>{setSort(e.target.value);setPage(1)}}><option>综合排序</option><option>销量优先</option><option>价格从低到高</option><option>评分优先</option></select><div className="view-switch"><button className={view==='grid'?'active':''} onClick={()=>setView('grid')}><Grid2X2 size={17}/></button><button className={view==='list'?'active':''} onClick={()=>setView('list')}><List size={17}/></button></div></div></div>{visible.length?<><div className={`product-grid catalog-products ${view}`}>{visible.map(p=><ProductCard key={p.id} product={p}/>)}</div><div className="pagination"><button disabled={page===1} onClick={()=>setPage(x=>Math.max(1,x-1))}>‹</button><button className="active">{page}</button><button disabled={page===pages} onClick={()=>setPage(x=>Math.min(pages,x+1))}>›</button></div></>:<div className="card empty-state"><div className="empty-illustration">⌕</div><h3>{loading?'正在加载商品':'没有找到符合条件的商品'}</h3><p>试试放宽价格或移除部分筛选条件。</p><button className="btn primary" onClick={reset}>清空筛选</button></div>}</section></div><Modal open={drawer} title="筛选商品" onClose={()=>setDrawer(false)} footer={<><button className="btn ghost" onClick={reset}>重置</button><button className="btn primary" onClick={()=>setDrawer(false)}>查看 {visible.length} 件商品</button></>}><Filters {...{category,setCategory,brand,setBrand,maxPrice,setMaxPrice}}/></Modal></div></div>
}