import type { Product } from '../types'
import { graphEdges, graphNodes, products } from '../mock/data'

const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000').replace(/\/$/, '')

interface ApiEnvelope<T> { success: boolean; data: T; message: string; request_id: string }
interface ApiProductListItem { id:number; product_code:string; name:string; subtitle:string|null; brand:string; category:string; merchant:string; main_image_url:string|null; sale_price:string|null; market_price:string|null; stock_quantity:number|null; audit_status:string; updated_at:string }
interface ApiProductDetail extends Omit<ApiProductListItem, 'merchant'> { description:string|null; raw_ingredient_text:string; allergen_notice:string|null; merchant:{merchant_code:string;name:string}; specs:Array<{spec_name:string;sale_price:string|null;market_price:string|null;stock_quantity:number|null}>; images:Array<{image_url:string}>; nutrition:Array<{nutrient_name:string;value:string|null}>; contains:Array<{name:string;entity_type:string}>; may_contain:Array<{name:string}> }
export interface ProductPage { total:number; page:number; page_size:number; items:Product[]; source:'api'|'mock' }
export interface ProductGraphData { nodes:Array<{data:{id:string;label:string;type:string;business_code?:string;risk_level?:string|null}}>; edges:Array<{data:{id:string;source:string;target:string;type?:string;label?:string;confidence?:number|null;source_code?:string|null;audit_status?:string|null}}>; summary?:{contains_count:number;may_contain_count:number;risk_count:number;information_status:string}; source:'api'|'mock' }

export interface NutritionTarget { nutrient_code:string|null; nutrient_name:string; operator:'LTE'|'GTE'; value:string; unit:string; basis:string }
export interface FilterAnalyzeData { category:string|null; category_code:string|null; exclude_ingredients:string[]; exclude_categories:string[]; nutrition_targets:NutritionTarget[]; max_price:string|null; preferences:string[]; parser:string; normalized_text:string; unparsed_fragments:string[]; source:'api'|'mock' }
export interface FilterSearchItem { product_code:string; name:string; brand:string; category:string; main_image_url:string|null; sale_price:string|null; match_status:'MATCH'|'RISK'|'NOT_MATCH'|'UNKNOWN'; reasons:string[]; contains_hits:string[]; may_contain_hits:string[] }
export interface FilterSearchData { total:number; page:number; page_size:number; items:Product[]; source:'api'|'mock' }

export const categoryLabels:Record<string,string>={CAT001:'早餐麦片',CAT002:'饼干糕点',CAT003:'乳品酸奶',CAT004:'坚果果干',CAT005:'果汁饮品',CAT006:'面包烘焙',CAT007:'巧克力',CAT008:'调味速食',CAT009:'谷物能量棒',CAT010:'植物蛋白'}
function mockAnalyzeFilter(text:string):FilterAnalyzeData{const negative=/(不含|不要|避免|排除|去掉|避开)\s*(果汁饮料|果汁|花生酱|花生粉|花生|鲜奶|奶制品|乳品|牛奶)/g;const excludeIngredients:string[]=[];const excludeCategories:string[]=[];let positiveText=text;for(const match of text.matchAll(negative)){const alias=match[2];if(alias==='果汁'||alias==='果汁饮料')excludeCategories.push('CAT005');else if(/花生/.test(alias))excludeIngredients.push('花生');else excludeIngredients.push('牛奶');positiveText=positiveText.replace(match[0],' ')}const categoryAliases:Array<[RegExp,string]>=[[/早餐麦片|早餐/,'CAT001'],[/饼干/,'CAT002'],[/奶制品|乳品|鲜奶|酸奶|牛奶/,'CAT003'],[/坚果/,'CAT004'],[/果汁饮料|果汁/,'CAT005'],[/面包/,'CAT006'],[/巧克力/,'CAT007'],[/速食/,'CAT008'],[/谷物棒/,'CAT009'],[/植物蛋白|植物奶/,'CAT010']];const categoryCode=categoryAliases.find(([pattern])=>pattern.test(positiveText))?.[1]||null;const nutrition:NutritionTarget[]=[];if(text.includes('高蛋白'))nutrition.push({nutrient_code:'NUT_PROTEIN',nutrient_name:'蛋白质',operator:'GTE',value:'8',unit:'g',basis:'PER_100G'});if(text.includes('低糖'))nutrition.push({nutrient_code:'NUT_SUGAR',nutrient_name:'糖',operator:'LTE',value:'5',unit:'g',basis:'PER_100G'});const price=text.match(/(\d+(?:\.\d+)?)\s*元/);return{category:categoryCode?categoryLabels[categoryCode]:null,category_code:categoryCode,exclude_ingredients:[...new Set(excludeIngredients)],exclude_categories:[...new Set(excludeCategories)],nutrition_targets:nutrition,max_price:price?.[1]||null,preferences:[...(text.includes('高蛋白')?['高蛋白']:[]),...(text.includes('低糖')?['低糖']:[]),...(text.includes('配料简单')?['配料简单']:[])],parser:'MOCK_FALLBACK',normalized_text:text.trim(),unparsed_fragments:[],source:'mock'}}
export async function analyzeFilter(text:string):Promise<FilterAnalyzeData>{console.log('[filter/analyze] request text:',text);try{const data=await request<Omit<FilterAnalyzeData,'category'|'preferences'|'source'>>('/api/v1/filter/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const preferences=[...data.nutrition_targets.map(x=>x.nutrient_name==='蛋白质'&&x.operator==='GTE'?'高蛋白':x.nutrient_name==='糖'&&x.operator==='LTE'?'低糖':x.operator==='GTE'?`高${x.nutrient_name}`:`低${x.nutrient_name}`),...(text.includes('配料简单')?['配料简单']:[])];const result:FilterAnalyzeData={...data,exclude_categories:data.exclude_categories||[],category:data.category_code?categoryLabels[data.category_code]||data.category_code:null,preferences,source:'api'};console.log('[filter/analyze] response data:',result);return result}catch(error){console.warn('[filter/analyze] API failed, using Mock fallback',error);const fallback=mockAnalyzeFilter(text);console.log('[filter/analyze] response data:',fallback);return fallback}}

const matchStatuses:Record<FilterSearchItem['match_status'],Product['status']>={MATCH:'完全匹配',RISK:'存在风险',NOT_MATCH:'不匹配',UNKNOWN:'信息不足'}
function mapFilterProduct(item:FilterSearchItem):Product{const id=Number(item.product_code.slice(2));const fallback=fallbackProduct(id);return{...fallback,id,productCode:item.product_code,name:item.name,brand:item.brand,category:item.category,image:item.main_image_url||fallback.image,price:item.sale_price==null?fallback.price:Number(item.sale_price),status:matchStatuses[item.match_status],reason:item.reasons.join('；'),evidence:[...item.contains_hits.map(x=>`明确含有${x}`),...item.may_contain_hits.map(x=>`可能含有${x}`)].join('；')||'结构化配料与营养证据已核对'}}
function mockSearchFilter(analysis:FilterAnalyzeData):FilterSearchData{const category=analysis.category;const excluded=analysis.exclude_ingredients;const excludedCategoryNames=new Set(analysis.exclude_categories.map(code=>categoryLabels[code]).filter(Boolean));const items=products.filter(product=>(!category||product.category===category)&&!excludedCategoryNames.has(product.category)).map(product=>{const contains=excluded.filter(name=>product.ingredients.some(value=>value.includes(name))||product.additives.some(value=>value.includes(name)));const may=excluded.filter(name=>product.mayContain.some(value=>value.includes(name)));const overPrice=analysis.max_price!==null&&product.price>Number(analysis.max_price);let status:Product['status']=contains.length||overPrice?'不匹配':may.length?'存在风险':product.unknown.length?'信息不足':'完全匹配';return{...product,productCode:productCodeOf(product),status,reason:contains.length?`明确含有排除成分：${contains.join('、')}`:may.length?`包装提示可能含有：${may.join('、')}`:overPrice?'价格超过上限':'满足当前本地筛选条件'}});return{total:items.length,page:1,page_size:20,items,source:'mock'}}
export async function searchFilter(analysis:FilterAnalyzeData):Promise<FilterSearchData>{const body={exclude_ingredients:analysis.exclude_ingredients,exclude_categories:analysis.exclude_categories,nutrition_targets:analysis.nutrition_targets,max_price:analysis.max_price,category_code:analysis.category_code,page:1,page_size:20};console.log('[filter/search] request conditions:',body);try{const data=await request<{total:number;page:number;page_size:number;items:FilterSearchItem[]}>('/api/v1/filter/search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result={...data,items:data.items.map(mapFilterProduct),source:'api' as const};console.log('[filter/search] response data:',result);return result}catch(error){console.warn('[filter/search] API failed, using Mock fallback',error);const fallback=mockSearchFilter(analysis);console.log('[filter/search] response data:',fallback);return fallback}}
async function request<T>(path:string,init?:RequestInit):Promise<T>{
  const response=await fetch(`${API_BASE_URL}${path}`,{...init,headers:{Accept:'application/json',...init?.headers}})
  if(!response.ok) throw new Error(`API request failed: ${response.status}`)
  const payload=await response.json() as ApiEnvelope<T>
  if(!payload.success) throw new Error(payload.message||'API request failed')
  return payload.data
}

export function productCodeOf(product:Product):string{return product.productCode||`FP${String(product.id).padStart(4,'0')}`}
export function resolveProductCode(routeValue?:string):string{if(routeValue?.match(/^FP\d{4,}$/i))return routeValue.toUpperCase();const id=Number(routeValue);return `FP${String(Number.isFinite(id)&&id>0?id:1).padStart(4,'0')}`}
function fallbackProduct(id:number):Product{return products.find(item=>item.id===id)||products[0]}
function nutritionValue(items:ApiProductDetail['nutrition'],names:string[]):number|null{const item=items.find(entry=>names.includes(entry.nutrient_name));return item?.value==null?null:Number(item.value)}
function mapListProduct(item:ApiProductListItem):Product{const fallback=fallbackProduct(item.id);return{...fallback,id:item.id,productCode:item.product_code,name:item.name,brand:item.brand,category:item.category,merchant:item.merchant,image:item.main_image_url||fallback.image,price:item.sale_price==null?fallback.price:Number(item.sale_price),originalPrice:item.market_price==null?undefined:Number(item.market_price),stock:item.stock_quantity??0,reviewStatus:item.audit_status==='APPROVED'?'已通过':fallback.reviewStatus,updatedAt:item.updated_at}}
function mapDetailProduct(item:ApiProductDetail):Product{const base=mapListProduct({...item,merchant:item.merchant.name});const spec=item.specs[0];const additives=item.contains.filter(x=>x.entity_type==='ADDITIVE').map(x=>x.name);const ingredients=item.contains.filter(x=>x.entity_type!=='ADDITIVE').map(x=>x.name);return{...base,merchant:item.merchant.name,price:spec?.sale_price==null?base.price:Number(spec.sale_price),originalPrice:spec?.market_price==null?base.originalPrice:Number(spec.market_price),stock:spec?.stock_quantity??base.stock,spec:spec?.spec_name||base.spec,image:item.images[0]?.image_url||base.image,gallery:item.images.map(x=>x.image_url),ingredients:ingredients.length?ingredients:base.ingredients,additives,mayContain:item.may_contain.map(x=>x.name),nutrition:{energy:nutritionValue(item.nutrition,['能量']),protein:nutritionValue(item.nutrition,['蛋白质']),fat:nutritionValue(item.nutrition,['脂肪']),sugar:nutritionValue(item.nutrition,['糖','碳水化合物']),sodium:nutritionValue(item.nutrition,['钠'])},evidence:item.raw_ingredient_text,reason:item.description||item.subtitle||base.reason}}

export async function getProducts(params:URLSearchParams):Promise<ProductPage>{try{const data=await request<{total:number;page:number;page_size:number;items:ApiProductListItem[]}>(`/api/v1/products?${params.toString()}`);return{...data,items:data.items.map(mapListProduct),source:'api'}}catch{const page=Number(params.get('page')||1),pageSize=Number(params.get('page_size')||20),keyword=params.get('keyword')?.toLowerCase();const filtered=products.filter(x=>!keyword||`${x.name}${x.brand}`.toLowerCase().includes(keyword));return{total:filtered.length,page,page_size:pageSize,items:filtered.slice((page-1)*pageSize,page*pageSize),source:'mock'}}}
export async function getProductDetail(routeValue?:string):Promise<{product:Product;source:'api'|'mock'}>{const code=resolveProductCode(routeValue);try{return{product:mapDetailProduct(await request<ApiProductDetail>(`/api/v1/products/${code}`)),source:'api'}}catch{return{product:{...fallbackProduct(Number(code.slice(2))),productCode:code},source:'mock'}}}
const labels:Record<string,string>={FOOD_PRODUCT_CONTAINS_INGREDIENT:'包含',FOOD_PRODUCT_MAY_CONTAIN:'可能含有',FOOD_PRODUCT_HAS_ADDITIVE:'含添加剂',FOOD_PRODUCT_HAS_NUTRIENT:'营养指标',FOOD_PRODUCT_BELONGS_TO_BRAND:'属于品牌',FOOD_PRODUCT_BELONGS_TO_CATEGORY:'属于分类',INGREDIENT_HAS_RISK:'关联风险'}
export async function getProductGraph(routeValue?:string):Promise<ProductGraphData>{const code=resolveProductCode(routeValue);try{const data=await request<Omit<ProductGraphData,'source'>>(`/api/v1/products/${code}/graph`);return{...data,source:'api',nodes:data.nodes.map(n=>({data:{...n.data,type:n.data.type.toLowerCase()}})),edges:data.edges.map(e=>({data:{...e.data,label:labels[e.data.type||'']||e.data.type||'关联'}}))}}catch{const product=fallbackProduct(Number(code.slice(2)));const rootId=`FoodProduct:${code}`;return{nodes:graphNodes.map(n=>n.data.type==='product'?{data:{...n.data,id:rootId,label:product.name,business_code:code}}:n),edges:graphEdges.map(e=>({data:{...e.data,source:e.data.source==='p1'?rootId:e.data.source}})),source:'mock',summary:{contains_count:0,may_contain_count:0,risk_count:0,information_status:'NOT_SYNCED'}}}}
