import type { Product } from '../types'
import { graphEdges, graphNodes, products } from '../mock/data'

export const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000').replace(/\/$/, '')
export const ACCESS_TOKEN_KEY = 'access_token'
export const getAccessToken = () => localStorage.getItem(ACCESS_TOKEN_KEY)
export const saveAccessToken = (token:string) => localStorage.setItem(ACCESS_TOKEN_KEY, token)

interface ApiEnvelope<T> { success: boolean; data: T; message: string; request_id: string }
interface ApiProductListItem { id:number; product_code:string; name:string; subtitle:string|null; brand:string; category:string; merchant:string; main_image_url:string|null; sale_price:string|null; market_price:string|null; stock_quantity:number|null; audit_status:string; updated_at:string }
export interface ApiProductIngredient { entity_code:string; name:string; entity_type:string; relation_type:'CONTAINS'|'MAY_CONTAIN'|'UNKNOWN'; confidence:string|null; source_code:string; audit_status:string }
export interface ApiProductNutrition { nutrient_code:string; nutrient_name:string; value:string|null; unit:string; basis:string; basis_quantity:string; source_code:string }
export interface ApiProductDetail {
  id:number; product_code:string; name:string; subtitle:string|null; description:string|null
  brand:string; brand_code:string; category:string; category_code:string
  merchant:{merchant_code:string;name:string}; raw_ingredient_text:string; allergen_notice:string|null
  ingredient_version:number|null; graph_sync_status:string
  specs:Array<{spec_code:string;spec_name:string;unit_name:string;net_content_value:string|null;net_content_unit:string|null;is_default:boolean;sale_price:string|null;market_price:string|null;currency:string|null;stock_quantity:number|null;sellable:boolean|null}>
  images:Array<{image_type:string;image_url:string;alt_text:string|null;sort_order:number}>
  nutrition:ApiProductNutrition[]; contains:ApiProductIngredient[]; may_contain:ApiProductIngredient[]; unknown:ApiProductIngredient[]
  sales_count:number; average_rating:string|null; review_count:number
  match_status:string; match_reason:string|null; evidence_text:string|null; info_source:string|null
  audit_status:string; sale_status:string; created_at:string; updated_at:string
}
export interface ProductGraphData { nodes:Array<{data:{id:string;label:string;type:string;business_code?:string;risk_level?:string|null}}>; edges:Array<{data:{id:string;source:string;target:string;type?:string;label?:string;confidence?:number|null;source_code?:string|null;audit_status?:string|null}}>; summary?:{contains_count:number;may_contain_count:number;risk_count:number;information_status:string}; source:'api'|'mock' }

export interface NutritionTarget { nutrient_code:string|null; nutrient_name:string; operator:'LTE'|'GTE'; value:string; unit:string; basis:'PER_100G'|'PER_100ML' }
export interface FilterConditionsData { exclude_ingredients:string[]; exclude_categories:string[]; preferred_ingredients:string[]; nutrition_targets:NutritionTarget[]; max_price:string|null; category_code:string|null }
export interface FilterAnalyzeData extends FilterConditionsData { category:string|null; parser:string; normalized_text:string; unparsed_fragments:string[]; source:'api'|'mock' }
export interface FilterReason { source:'exclude'|'nutrition'|'price'|'unknown'|'preference'|'match'; message:string }
export interface FilterSearchItem { product_code:string; name:string; brand:string; category:string; main_image_url:string|null; sale_price:string|null; match_status:'MATCH'|'RISK'|'NOT_MATCH'|'UNKNOWN'; reason:string; reason_source:FilterReason['source']; reasons:string[]; reason_details:FilterReason[]; contains_hits:string[]; may_contain_hits:string[]; preference_hits:string[] }
export interface FilterSearchData { total:number; page:number; page_size:number; conditions:FilterConditionsData; items:Product[]; source:'api'|'mock' }

export const emptyFilterConditions=():FilterConditionsData=>({exclude_ingredients:[],exclude_categories:[],preferred_ingredients:[],nutrition_targets:[],max_price:null,category_code:null})
export const categoryLabels:Record<string,string>={CAT001:'早餐麦片',CAT002:'饼干糕点',CAT003:'乳品酸奶',CAT004:'坚果果干',CAT005:'果汁饮品',CAT006:'面包烘焙',CAT007:'巧克力',CAT008:'调味速食',CAT009:'谷物能量棒',CAT010:'植物蛋白'}
const nutrientMeta:Record<string,{code:string;name:string;operator:'LTE'|'GTE';unit:string}>={sugar:{code:'NUT_SUGAR',name:'糖',operator:'LTE',unit:'g'},fat:{code:'NUT_FAT',name:'脂肪',operator:'LTE',unit:'g'},protein:{code:'NUT_PROTEIN',name:'蛋白质',operator:'GTE',unit:'g'},sodium:{code:'NUT_SODIUM',name:'钠',operator:'LTE',unit:'mg'}}
function dynamicTargets(text:string):NutritionTarget[]{const patterns:Array<[keyof typeof nutrientMeta,RegExp]>=[['sugar',/糖[^0-9]{0,8}(?:不超过|低于|≤|小于)\s*(\d+(?:\.\d+)?)/],['fat',/脂肪[^0-9]{0,8}(?:不超过|低于|≤|小于)\s*(\d+(?:\.\d+)?)/],['protein',/蛋白质[^0-9]{0,8}(?:不少于|高于|≥|大于)\s*(\d+(?:\.\d+)?)/],['sodium',/钠[^0-9]{0,8}(?:不超过|低于|≤|小于)\s*(\d+(?:\.\d+)?)/]];return patterns.flatMap(([key,pattern])=>{const match=text.match(pattern);if(!match)return[];const meta=nutrientMeta[key];return[{nutrient_code:meta.code,nutrient_name:meta.name,operator:meta.operator,value:match[1],unit:meta.unit,basis:'PER_100G'}]})}
function mockAnalyzeFilter(text:string):FilterAnalyzeData{const conditions=emptyFilterConditions();const negative=/(不含|不要|避免|排除|去掉|避开)\s*(果汁饮料|果汁|花生酱|花生粉|花生|鲜奶|奶制品|乳品|牛奶)/g;let positive=text;for(const match of text.matchAll(negative)){const alias=match[2];if(alias.includes('果汁'))conditions.exclude_categories.push('CAT005');else conditions.exclude_ingredients.push(alias.includes('花生')?'花生':'牛奶');positive=positive.replace(match[0],' ')}const aliases:Array<[RegExp,string]>=[[/早餐麦片|早餐/,'CAT001'],[/饼干/,'CAT002'],[/奶制品|乳品|鲜奶|酸奶|牛奶/,'CAT003'],[/坚果/,'CAT004'],[/果汁饮料|果汁/,'CAT005'],[/面包/,'CAT006'],[/巧克力/,'CAT007'],[/速食/,'CAT008'],[/谷物棒/,'CAT009'],[/植物蛋白|植物奶/,'CAT010']];conditions.category_code=aliases.find(([pattern])=>pattern.test(positive))?.[1]||null;conditions.nutrition_targets=dynamicTargets(text);if(text.includes('高蛋白'))conditions.preferred_ingredients.push('高蛋白');const price=text.match(/(\d+(?:\.\d+)?)\s*元(?:以内|以下)?/);conditions.max_price=price?.[1]||null;return{...conditions,category:conditions.category_code?categoryLabels[conditions.category_code]||conditions.category_code:null,parser:'MOCK_FALLBACK',normalized_text:text.trim(),unparsed_fragments:[],source:'mock'}}
export async function analyzeFilter(text:string):Promise<FilterAnalyzeData>{console.log('[filter/analyze] request text:',text);try{const data=await request<Omit<FilterAnalyzeData,'category'|'source'>>('/api/v1/filter/analyze',{method:'POST',body:JSON.stringify({text})});const result={...data,category:data.category_code?categoryLabels[data.category_code]||data.category_code:null,source:'api' as const};console.log('[filter/analyze] response data:',result);return result}catch(error){console.warn('[filter/analyze] API failed, using controlled local fallback',error);return mockAnalyzeFilter(text)}}

const matchStatuses:Record<FilterSearchItem['match_status'],Product['status']>={MATCH:'完全匹配',RISK:'存在风险',NOT_MATCH:'不匹配',UNKNOWN:'信息不足'}
function mapFilterProduct(item:FilterSearchItem):Product{const id=Number(item.product_code.slice(2));const fallback=fallbackProduct(id);return{...fallback,id,productCode:item.product_code,name:item.name,brand:item.brand,category:item.category,image:item.main_image_url||fallback.image,price:item.sale_price==null?fallback.price:Number(item.sale_price),status:matchStatuses[item.match_status],reason:item.reason,evidence:item.reason_details.map(reason=>`[${reason.source}] ${reason.message}`).join('；')}}
function mockSearchFilter(conditions:FilterConditionsData):FilterSearchData{const excludedCategories=new Set(conditions.exclude_categories.map(code=>categoryLabels[code]).filter(Boolean));const productsWithScore=products.filter(product=>(!conditions.category_code||product.category===categoryLabels[conditions.category_code])&&!excludedCategories.has(product.category)).map(product=>{const contains=conditions.exclude_ingredients.filter(name=>[...product.ingredients,...product.additives].some(value=>value.includes(name)));const may=conditions.exclude_ingredients.filter(name=>product.mayContain.some(value=>value.includes(name)));const reasons:FilterReason[]=[];let status:FilterSearchItem['match_status']='MATCH';if(contains.length){status='NOT_MATCH';reasons.push({source:'exclude',message:`含有用户排除成分：${contains.join('、')}`})}else if(may.length){status='RISK';reasons.push({source:'exclude',message:`可能含有用户排除成分：${may.join('、')}`})}const facts:Record<string,number|null>={NUT_SUGAR:product.nutrition.sugar,NUT_FAT:product.nutrition.fat,NUT_PROTEIN:product.nutrition.protein,NUT_SODIUM:product.nutrition.sodium};for(const target of conditions.nutrition_targets){const value=target.nutrient_code?facts[target.nutrient_code]:null;if(value===null||value===undefined){if(status==='MATCH')status='UNKNOWN';reasons.push({source:'unknown',message:`${target.nutrient_name}暂无数据`});continue}const failed=target.operator==='LTE'?value>Number(target.value):value<Number(target.value);if(failed){status='NOT_MATCH';reasons.push({source:'nutrition',message:`${target.nutrient_name}${value}${target.unit}${target.operator==='LTE'?'超过限制':'低于限制'}${target.value}${target.unit}`})}}if(conditions.max_price!==null&&product.price>Number(conditions.max_price)){status='NOT_MATCH';reasons.push({source:'price',message:`价格${product.price}元超过限制${conditions.max_price}元`})}const preferenceHits=conditions.preferred_ingredients.filter(name=>name==='高蛋白'?(product.nutrition.protein??0)>0:product.ingredients.some(value=>value.includes(name)));if(preferenceHits.length)reasons.push({source:'preference',message:`匹配偏好成分：${preferenceHits.join('、')}`});if(!reasons.length)reasons.push({source:'match',message:'满足当前生效条件'});return{product:{...product,productCode:productCodeOf(product),status:matchStatuses[status],reason:reasons[0].message,evidence:reasons.map(reason=>`[${reason.source}] ${reason.message}`).join('；')},score:preferenceHits.length}}).sort((a,b)=>b.score-a.score);return{total:productsWithScore.length,page:1,page_size:20,conditions,items:productsWithScore.map(value=>value.product),source:'mock'}}
export async function searchFilter(conditions:FilterConditionsData):Promise<FilterSearchData>{const body={...conditions,page:1,page_size:20};console.log('[filter/search] request conditions:',body);try{const data=await request<{total:number;page:number;page_size:number;conditions:FilterConditionsData;items:FilterSearchItem[]}>('/api/v1/filter/search',{method:'POST',body:JSON.stringify(body)});return{...data,items:data.items.map(mapFilterProduct),source:'api'}}catch(error){console.warn('[filter/search] API failed, using controlled local fallback',error);return mockSearchFilter(conditions)}}
export async function apiRequest<T>(path:string,init?:RequestInit):Promise<T>{
  const token=getAccessToken()
  const url=`${API_BASE_URL}${path}`
  const headers=new Headers(init?.headers)
  headers.set('Accept','application/json')
  headers.set('Content-Type','application/json')
  if(token)headers.set('Authorization',`Bearer ${token}`)
  console.log('[api] request',{url,hasToken:Boolean(token)})
  console.log('[api] headers',headers)
  const response=await fetch(url,{...init,headers})
  console.log('[api] response',{url,status:response.status})
  if(response.status===401){localStorage.removeItem(ACCESS_TOKEN_KEY);if(window.location.pathname!=='/login')window.location.assign('/login')}
  const payload=await response.json() as ApiEnvelope<T>&{error?:{message?:string}}
  if(!response.ok||!payload.success)throw new Error(payload.error?.message||payload.message||`API request failed: ${response.status}`)
  return payload.data
}
const request=apiRequest

export function productCodeOf(product:{id:number;productCode?:string}):string{return product.productCode||`FP${String(product.id).padStart(4,'0')}`}
export function resolveProductCode(routeValue?:string):string{if(routeValue?.match(/^FP\d{4,}$/i))return routeValue.toUpperCase();const id=Number(routeValue);return `FP${String(Number.isFinite(id)&&id>0?id:1).padStart(4,'0')}`}
function fallbackProduct(id:number):Product{return products.find(item=>item.id===id)||products[0]}
function mapListProduct(item:ApiProductListItem):Product{const fallback=fallbackProduct(item.id);return{...fallback,id:item.id,productCode:item.product_code,name:item.name,brand:item.brand,category:item.category,merchant:item.merchant,image:item.main_image_url||fallback.image,price:item.sale_price==null?fallback.price:Number(item.sale_price),originalPrice:item.market_price==null?undefined:Number(item.market_price),stock:item.stock_quantity??0,reviewStatus:item.audit_status==='APPROVED'?'已通过':fallback.reviewStatus,updatedAt:item.updated_at}}

export async function getProductDetail(routeValue?:string):Promise<ApiProductDetail>{const code=resolveProductCode(routeValue);return request<ApiProductDetail>(`/api/v1/products/${code}`)}
const labels:Record<string,string>={FOOD_PRODUCT_CONTAINS_INGREDIENT:'包含',FOOD_PRODUCT_MAY_CONTAIN:'可能含有',FOOD_PRODUCT_HAS_ADDITIVE:'含添加剂',FOOD_PRODUCT_HAS_NUTRIENT:'营养指标',FOOD_PRODUCT_BELONGS_TO_BRAND:'属于品牌',FOOD_PRODUCT_BELONGS_TO_CATEGORY:'属于分类',INGREDIENT_HAS_RISK:'关联风险'}
export async function getProductGraph(routeValue?:string):Promise<ProductGraphData>{const code=resolveProductCode(routeValue);try{const data=await request<Omit<ProductGraphData,'source'>>(`/api/v1/products/${code}/graph`);return{...data,source:'api',nodes:data.nodes.map(n=>({data:{...n.data,type:n.data.type.toLowerCase()}})),edges:data.edges.map(e=>({data:{...e.data,label:labels[e.data.type||'']||e.data.type||'关联'}}))}}catch{const product=fallbackProduct(Number(code.slice(2)));const rootId=`FoodProduct:${code}`;return{nodes:graphNodes.map(n=>n.data.type==='product'?{data:{...n.data,id:rootId,label:product.name,business_code:code}}:n),edges:graphEdges.map(e=>({data:{...e.data,source:e.data.source==='p1'?rootId:e.data.source}})),source:'mock',summary:{contains_count:0,may_contain_count:0,risk_count:0,information_status:'NOT_SYNCED'}}}}
