import type { Product } from '../types'
import { graphEdges, graphNodes, products } from '../mock/data'

const API_BASE_URL = (import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000').replace(/\/$/, '')

interface ApiEnvelope<T> { success: boolean; data: T; message: string; request_id: string }
interface ApiProductListItem { id:number; product_code:string; name:string; subtitle:string|null; brand:string; category:string; merchant:string; main_image_url:string|null; sale_price:string|null; market_price:string|null; stock_quantity:number|null; audit_status:string; updated_at:string }
interface ApiProductDetail extends Omit<ApiProductListItem, 'merchant'> { description:string|null; raw_ingredient_text:string; allergen_notice:string|null; merchant:{merchant_code:string;name:string}; specs:Array<{spec_name:string;sale_price:string|null;market_price:string|null;stock_quantity:number|null}>; images:Array<{image_url:string}>; nutrition:Array<{nutrient_name:string;value:string|null}>; contains:Array<{name:string;entity_type:string}>; may_contain:Array<{name:string}> }
export interface ProductPage { total:number; page:number; page_size:number; items:Product[]; source:'api'|'mock' }
export interface ProductGraphData { nodes:Array<{data:{id:string;label:string;type:string;business_code?:string;risk_level?:string|null}}>; edges:Array<{data:{id:string;source:string;target:string;type?:string;label?:string;confidence?:number|null;source_code?:string|null;audit_status?:string|null}}>; summary?:{contains_count:number;may_contain_count:number;risk_count:number;information_status:string}; source:'api'|'mock' }

async function request<T>(path:string):Promise<T>{
  const response=await fetch(`${API_BASE_URL}${path}`,{headers:{Accept:'application/json'}})
  if(!response.ok) throw new Error(`API request failed: ${response.status}`)
  const payload=await response.json() as ApiEnvelope<T>
  if(!payload.success) throw new Error(payload.message||'API request failed')
  return payload.data
}

export function productCodeOf(product:Product):string{return product.productCode||`FP${String(product.id).padStart(4,'0')}`}
export function resolveProductCode(routeValue?:string):string{if(routeValue?.match(/^FP\d{4,}$/i))return routeValue.toUpperCase();const id=Number(routeValue);return `FP${String(Number.isFinite(id)&&id>0?id:1).padStart(4,'0')}`}
function fallbackProduct(id:number):Product{return products.find(item=>item.id===id)||products[0]}
function nutritionValue(items:ApiProductDetail['nutrition'],names:string[]):number|null{const item=items.find(entry=>names.includes(entry.nutrient_name));return item?.value==null?null:Number(item.value)}
function mapListProduct(item:ApiProductListItem):Product{const fallback=fallbackProduct(item.id);return{...fallback,id:item.id,productCode:item.product_code,name:item.name,brand:item.brand,category:item.category,merchant:item.merchant,image:item.main_image_url||fallback.image,price:item.sale_price==null?fallback.price:Number(item.sale_price),originalPrice:item.market_price==null?undefined:Number(item.market_price),stock:item.stock_quantity??0,reviewStatus:item.audit_status==='APPROVED'?'已通过':fallback.reviewStatus,updatedAt:item.updated_at}}
function mapDetailProduct(item:ApiProductDetail):Product{const base=mapListProduct({...item,merchant:item.merchant.name});const spec=item.specs[0];const additives=item.contains.filter(x=>x.entity_type==='ADDITIVE').map(x=>x.name);const ingredients=item.contains.filter(x=>x.entity_type!=='ADDITIVE').map(x=>x.name);return{...base,merchant:item.merchant.name,price:spec?.sale_price==null?base.price:Number(spec.sale_price),originalPrice:spec?.market_price==null?base.originalPrice:Number(spec.market_price),stock:spec?.stock_quantity??base.stock,spec:spec?.spec_name||base.spec,image:item.images[0]?.image_url||base.image,gallery:item.images.map(x=>x.image_url),ingredients:ingredients.length?ingredients:base.ingredients,additives,mayContain:item.may_contain.map(x=>x.name),nutrition:{energy:nutritionValue(item.nutrition,['能量']),protein:nutritionValue(item.nutrition,['蛋白质']),fat:nutritionValue(item.nutrition,['脂肪']),sugar:nutritionValue(item.nutrition,['糖','碳水化合物']),sodium:nutritionValue(item.nutrition,['钠'])},evidence:item.raw_ingredient_text,reason:item.description||item.subtitle||base.reason}}

export async function getProducts(params:URLSearchParams):Promise<ProductPage>{try{const data=await request<{total:number;page:number;page_size:number;items:ApiProductListItem[]}>(`/api/v1/products?${params.toString()}`);return{...data,items:data.items.map(mapListProduct),source:'api'}}catch{const page=Number(params.get('page')||1),pageSize=Number(params.get('page_size')||20),keyword=params.get('keyword')?.toLowerCase();const filtered=products.filter(x=>!keyword||`${x.name}${x.brand}`.toLowerCase().includes(keyword));return{total:filtered.length,page,page_size:pageSize,items:filtered.slice((page-1)*pageSize,page*pageSize),source:'mock'}}}
export async function getProductDetail(routeValue?:string):Promise<{product:Product;source:'api'|'mock'}>{const code=resolveProductCode(routeValue);try{return{product:mapDetailProduct(await request<ApiProductDetail>(`/api/v1/products/${code}`)),source:'api'}}catch{return{product:{...fallbackProduct(Number(code.slice(2))),productCode:code},source:'mock'}}}
const labels:Record<string,string>={FOOD_PRODUCT_CONTAINS_INGREDIENT:'包含',FOOD_PRODUCT_MAY_CONTAIN:'可能含有',FOOD_PRODUCT_HAS_ADDITIVE:'含添加剂',FOOD_PRODUCT_HAS_NUTRIENT:'营养指标',FOOD_PRODUCT_BELONGS_TO_BRAND:'属于品牌',FOOD_PRODUCT_BELONGS_TO_CATEGORY:'属于分类',INGREDIENT_HAS_RISK:'关联风险'}
export async function getProductGraph(routeValue?:string):Promise<ProductGraphData>{const code=resolveProductCode(routeValue);try{const data=await request<Omit<ProductGraphData,'source'>>(`/api/v1/products/${code}/graph`);return{...data,source:'api',nodes:data.nodes.map(n=>({data:{...n.data,type:n.data.type.toLowerCase()}})),edges:data.edges.map(e=>({data:{...e.data,label:labels[e.data.type||'']||e.data.type||'关联'}}))}}catch{const product=fallbackProduct(Number(code.slice(2)));const rootId=`FoodProduct:${code}`;return{nodes:graphNodes.map(n=>n.data.type==='product'?{data:{...n.data,id:rootId,label:product.name,business_code:code}}:n),edges:graphEdges.map(e=>({data:{...e.data,source:e.data.source==='p1'?rootId:e.data.source}})),source:'mock',summary:{contains_count:0,may_contain_count:0,risk_count:0,information_status:'NOT_SYNCED'}}}}