import { CheckCircle2, Pencil, Plus, Trash2 } from 'lucide-react'
import { useEffect, useState } from 'react'
import { createAddress, deleteAddress, listAddresses, setDefaultAddress, updateAddress, type AddressWrite, type ApiAddress } from '../../services/commerce'
import { useApp } from '../../store/AppStore'
import { ConfirmButton, EmptyState, LoadingBlock, Modal } from '../common/UI'
import { AddressForm } from './AddressForm'

export function AddressList({selectable=false,selectedCode='',onSelect,onLoaded}:{selectable?:boolean;selectedCode?:string;onSelect?:(code:string)=>void;onLoaded?:(items:ApiAddress[])=>void}){
 const {notify}=useApp();const [items,setItems]=useState<ApiAddress[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [editing,setEditing]=useState<ApiAddress|null|undefined>(undefined)
 const reload=async()=>{const values=await listAddresses();setItems(values);onLoaded?.(values);return values}
 useEffect(()=>{reload().catch(error=>notify(error instanceof Error?error.message:'地址加载失败','error')).finally(()=>setLoading(false))},[])
 const save=async(payload:AddressWrite)=>{setSaving(true);try{if(editing)await updateAddress(editing.address_code,payload);else await createAddress(payload);await reload();setEditing(undefined);notify(editing?'地址已更新':'地址已新增')}catch(error){notify(error instanceof Error?error.message:'地址保存失败','error')}finally{setSaving(false)}}
 const remove=async(code:string)=>{try{await deleteAddress(code);await reload();notify('地址已删除','info')}catch(error){notify(error instanceof Error?error.message:'地址删除失败','error')}}
 const makeDefault=async(code:string)=>{try{await setDefaultAddress(code);await reload();onSelect?.(code);notify('默认地址已更新')}catch(error){notify(error instanceof Error?error.message:'默认地址更新失败','error')}}
 if(loading)return <LoadingBlock text="正在读取收货地址…"/>
 return <div><div className="section-title" style={{marginBottom:14}}><div><h2>收货地址</h2><p>地址数据来自当前登录用户的账户。</p></div><button className="btn ghost" onClick={()=>setEditing(null)}><Plus size={15}/>新增地址</button></div>{items.length?items.map(address=>{const selected=selectable?selectedCode===address.address_code:address.is_default;return <div className={`address-card ${selected?'selected':''}`} key={address.address_code} onClick={()=>selectable&&onSelect?.(address.address_code)}><span><b>{address.receiver_name} · {address.receiver_phone}</b><p>{address.province}{address.city}{address.district}{address.detail_address}</p><small>{address.is_default?'默认地址':'普通地址'}{address.postal_code?` · ${address.postal_code}`:''}</small></span><div style={{display:'flex',gap:6,alignItems:'center'}}>{selected&&<CheckCircle2 color="var(--sage)"/>}<button className="icon-btn" aria-label="编辑地址" onClick={event=>{event.stopPropagation();setEditing(address)}}><Pencil size={15}/></button>{!address.is_default&&<button className="text-button" onClick={event=>{event.stopPropagation();void makeDefault(address.address_code)}}>设为默认</button>}<span onClick={event=>event.stopPropagation()}><ConfirmButton className="icon-btn" confirmText="确定删除这个地址？" onConfirm={()=>void remove(address.address_code)}><Trash2 size={15}/></ConfirmButton></span></div></div>}):<EmptyState title="还没有收货地址" text="新增地址后可在结算时直接选择。" action={<button className="btn primary" onClick={()=>setEditing(null)}>新增收货地址</button>}/>}<Modal open={editing!==undefined} title={editing?'编辑收货地址':'新增收货地址'} onClose={()=>setEditing(undefined)}>{editing!==undefined&&<AddressForm key={editing?.address_code||'new'} initial={editing} submitting={saving} onCancel={()=>setEditing(undefined)} onSubmit={save}/>}</Modal></div>
}
