import React from 'react'
import { RotateCcw, X } from 'lucide-react'
import type { BrandOption, CategoryCount, ProductQuery } from '../../services/productCatalog'

type FilterValue=Omit<ProductQuery,'page'|'pageSize'|'sortBy'|'sortOrder'|'keyword'>
export function ProductFilterPanel({value,categories,brands,onChange,onReset}:{value:FilterValue;categories:CategoryCount[];brands:BrandOption[];onChange:(patch:Partial<FilterValue>)=>void;onReset:()=>void}){
 const [ingredient,setIngredient]=React.useState('')
 const addIngredient=()=>{const name=ingredient.trim();if(name&&!value.excludedIngredients.includes(name))onChange({excludedIngredients:[...value.excludedIngredients,name]});setIngredient('')}
 return <><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h3>筛选条件</h3><button className="icon-btn" onClick={onReset} title="清空全部"><RotateCcw size={16}/></button></div><div className="filter-group"><h4>商品分类</h4><div className="check-list"><label><input type="radio" checked={!value.category} onChange={()=>onChange({category:undefined})}/>全部分类</label>{categories.map(item=><label key={item.category_code}><input type="radio" checked={value.category===item.category_name} onChange={()=>onChange({category:item.category_name})}/>{item.category_name}<span className="filter-count">{item.product_count}</span></label>)}</div></div><div className="filter-group"><h4>品牌</h4><select className="select" value={value.brand||''} onChange={e=>onChange({brand:e.target.value||undefined})}><option value="">全部品牌</option>{brands.map(item=><option key={item.brand_code} value={item.name}>{item.name}</option>)}</select></div><div className="filter-group"><h4>价格区间</h4><div className="range-row"><input className="input" type="number" min="0" value={value.priceMin??''} onChange={e=>onChange({priceMin:e.target.value===''?undefined:Number(e.target.value)})} placeholder="最低价"/><span>—</span><input className="input" type="number" min="0" value={value.priceMax??''} onChange={e=>onChange({priceMax:e.target.value===''?undefined:Number(e.target.value)})} placeholder="最高价"/></div></div><div className="filter-group"><h4>排除成分</h4><div style={{display:'flex',gap:6}}><input className="input" value={ingredient} onChange={e=>setIngredient(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addIngredient()} placeholder="输入成分名称"/><button className="btn outline" onClick={addIngredient}>添加</button></div><div className="tag-row" style={{marginTop:8}}>{value.excludedIngredients.map(name=><button className="chip hard" key={name} onClick={()=>onChange({excludedIngredients:value.excludedIngredients.filter(x=>x!==name)})}>{name}<X size={12}/></button>)}</div></div><div className="filter-group"><h4>营养范围（每100g/mL）</h4><div className="check-list"><label><input type="checkbox" checked={value.sugarMax===5} onChange={e=>onChange({sugarMax:e.target.checked?5:undefined})}/>糖 ≤ 5g</label><label><input type="checkbox" checked={value.fatMax===10} onChange={e=>onChange({fatMax:e.target.checked?10:undefined})}/>脂肪 ≤ 10g</label><label><input type="checkbox" checked={value.proteinMin===8} onChange={e=>onChange({proteinMin:e.target.checked?8:undefined})}/>蛋白质 ≥ 8g</label><label><input type="checkbox" checked={value.sodiumMax===500} onChange={e=>onChange({sodiumMax:e.target.checked?500:undefined})}/>钠 ≤ 500mg</label></div></div></>
}
