-- FoodPlatform schema. Tested with MySQL 9.7.1.
-- Database: food_platform
SET NAMES utf8mb4;
SET time_zone = '+08:00';

CREATE DATABASE IF NOT EXISTS food_platform
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;
USE food_platform;

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '内部用户主键',
  user_code VARCHAR(32) NOT NULL COMMENT '跨系统用户业务编码',
  username VARCHAR(64) NOT NULL COMMENT '登录账号',
  password_hash VARCHAR(255) NOT NULL COMMENT '强哈希密码，不保存明文',
  phone VARCHAR(32) NULL,
  email VARCHAR(128) NULL,
  user_type VARCHAR(32) NOT NULL DEFAULT 'CONSUMER' COMMENT 'CONSUMER/MERCHANT/ADMIN/KNOWLEDGE_ADMIN/OPS',
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE/FROZEN/PENDING/DISABLED',
  last_login_at DATETIME(3) NULL,
  password_changed_at DATETIME(3) NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_user_code (user_code),
  UNIQUE KEY uk_sys_user_username (username),
  UNIQUE KEY uk_sys_user_phone (phone),
  UNIQUE KEY uk_sys_user_email (email),
  KEY idx_sys_user_type_status (user_type, status),
  KEY idx_sys_user_created_at (created_at)
) ENGINE=InnoDB COMMENT='系统用户与认证账号';

CREATE TABLE IF NOT EXISTS sys_role (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  role_code VARCHAR(40) NOT NULL,
  role_name VARCHAR(80) NOT NULL,
  description VARCHAR(255) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_role_code (role_code)
) ENGINE=InnoDB COMMENT='角色定义';

CREATE TABLE IF NOT EXISTS sys_permission (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  permission_code VARCHAR(80) NOT NULL,
  permission_name VARCHAR(120) NOT NULL,
  resource_type VARCHAR(32) NOT NULL DEFAULT 'API',
  description VARCHAR(255) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_permission_code (permission_code)
) ENGINE=InnoDB COMMENT='权限定义';

CREATE TABLE IF NOT EXISTS sys_user_role (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  role_id BIGINT UNSIGNED NOT NULL,
  granted_by BIGINT UNSIGNED NULL,
  expires_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_sys_user_role (user_id, role_id),
  KEY idx_sys_user_role_role (role_id),
  CONSTRAINT fk_sys_user_role_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE,
  CONSTRAINT fk_sys_user_role_role FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE RESTRICT,
  CONSTRAINT fk_sys_user_role_grantor FOREIGN KEY (granted_by) REFERENCES sys_user(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='用户角色关联';

CREATE TABLE IF NOT EXISTS sys_role_permission (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  role_id BIGINT UNSIGNED NOT NULL,
  permission_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_role_permission (role_id, permission_id),
  KEY idx_role_permission_permission (permission_id),
  CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE CASCADE,
  CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES sys_permission(id) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='角色权限关联';

CREATE TABLE IF NOT EXISTS user_profile (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  nickname VARCHAR(80) NOT NULL,
  avatar_url VARCHAR(1024) NULL,
  gender VARCHAR(16) NULL,
  birthday DATE NULL,
  bio VARCHAR(500) NULL,
  preference_completion TINYINT UNSIGNED NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_profile_user (user_id),
  CONSTRAINT fk_user_profile_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='用户资料';

CREATE TABLE IF NOT EXISTS user_address (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  address_code VARCHAR(40) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  receiver_name VARCHAR(80) NOT NULL,
  receiver_phone VARCHAR(32) NOT NULL,
  province VARCHAR(64) NOT NULL,
  city VARCHAR(64) NOT NULL,
  district VARCHAR(64) NOT NULL,
  detail_address VARCHAR(255) NOT NULL,
  postal_code VARCHAR(16) NULL,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_address_code (address_code),
  KEY idx_user_address_user_default (user_id, is_default, is_deleted),
  CONSTRAINT fk_user_address_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='用户收货地址';

CREATE TABLE IF NOT EXISTS user_ingredient_preference (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  preference_code VARCHAR(40) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  preference_type VARCHAR(16) NOT NULL COMMENT 'EXCLUDE/PREFER',
  ingredient_code VARCHAR(40) NOT NULL COMMENT '与Neo4j Ingredient统一的业务编码',
  ingredient_name VARCHAR(120) NOT NULL,
  strength TINYINT UNSIGNED NOT NULL DEFAULT 100 COMMENT '0-100，EXCLUDE默认100',
  is_enabled TINYINT(1) NOT NULL DEFAULT 1,
  preference_source VARCHAR(32) NOT NULL DEFAULT 'USER_INPUT',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_user_preference_code (preference_code),
  UNIQUE KEY uk_user_preference_target (user_id, preference_type, ingredient_code),
  KEY idx_preference_ingredient (ingredient_code, preference_type, is_enabled),
  CONSTRAINT fk_user_preference_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE,
  CONSTRAINT chk_preference_type CHECK (preference_type IN ('EXCLUDE','PREFER')),
  CONSTRAINT chk_preference_strength CHECK (strength BETWEEN 0 AND 100)
) ENGINE=InnoDB COMMENT='用户成分排除与偏好设置';

CREATE TABLE IF NOT EXISTS merchant (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  merchant_code VARCHAR(32) NOT NULL,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  merchant_name VARCHAR(120) NOT NULL,
  license_no VARCHAR(80) NOT NULL,
  contact_name VARCHAR(80) NOT NULL,
  contact_phone VARCHAR(32) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/ACTIVE/FROZEN/REJECTED',
  approved_by BIGINT UNSIGNED NULL,
  approved_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_merchant_code (merchant_code),
  UNIQUE KEY uk_merchant_owner (owner_user_id),
  UNIQUE KEY uk_merchant_license (license_no),
  KEY idx_merchant_status (status),
  CONSTRAINT fk_merchant_owner FOREIGN KEY (owner_user_id) REFERENCES sys_user(id) ON DELETE RESTRICT,
  CONSTRAINT fk_merchant_approver FOREIGN KEY (approved_by) REFERENCES sys_user(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='商家主体';

CREATE TABLE IF NOT EXISTS brand (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  brand_code VARCHAR(32) NOT NULL,
  merchant_id BIGINT UNSIGNED NULL,
  brand_name VARCHAR(120) NOT NULL,
  logo_url VARCHAR(1024) NULL,
  description VARCHAR(500) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  neo4j_node_key VARCHAR(64) NOT NULL COMMENT 'Neo4j业务节点键，默认brand_code',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_brand_code (brand_code),
  UNIQUE KEY uk_brand_name (brand_name),
  UNIQUE KEY uk_brand_neo4j_key (neo4j_node_key),
  KEY idx_brand_merchant_status (merchant_id, status),
  CONSTRAINT fk_brand_merchant FOREIGN KEY (merchant_id) REFERENCES merchant(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='商品品牌';

CREATE TABLE IF NOT EXISTS category (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  category_code VARCHAR(32) NOT NULL,
  parent_id BIGINT UNSIGNED NULL,
  category_name VARCHAR(120) NOT NULL,
  category_level TINYINT UNSIGNED NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  neo4j_node_key VARCHAR(64) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_category_code (category_code),
  UNIQUE KEY uk_category_parent_name (parent_id, category_name),
  UNIQUE KEY uk_category_neo4j_key (neo4j_node_key),
  KEY idx_category_parent_status (parent_id, status),
  CONSTRAINT fk_category_parent FOREIGN KEY (parent_id) REFERENCES category(id) ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='商品分类树';

CREATE TABLE IF NOT EXISTS product (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_code VARCHAR(40) NOT NULL COMMENT 'MySQL与Neo4j统一商品业务ID',
  merchant_id BIGINT UNSIGNED NOT NULL,
  brand_id BIGINT UNSIGNED NOT NULL,
  category_id BIGINT UNSIGNED NOT NULL,
  product_name VARCHAR(200) NOT NULL,
  subtitle VARCHAR(255) NULL,
  description TEXT NULL,
  raw_ingredient_text TEXT NOT NULL COMMENT '商品包装上的原始配料文本，不被标准化结果覆盖',
  allergen_notice TEXT NULL,
  match_status VARCHAR(24) NOT NULL DEFAULT 'INFORMATION_INSUFFICIENT' COMMENT 'FULL_MATCH/RISK/NOT_MATCH/INFORMATION_INSUFFICIENT',
  match_reason VARCHAR(500) NULL,
  evidence_text VARCHAR(1000) NULL,
  info_source VARCHAR(500) NULL,
  sale_status VARCHAR(24) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/ON_SALE/OFF_SALE/SUSPENDED',
  review_status VARCHAR(24) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/PENDING/APPROVED/REJECTED/NEED_MORE_INFO',
  neo4j_node_key VARCHAR(64) NOT NULL COMMENT '默认等于product_code，不使用Neo4j内部ID',
  graph_sync_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  graph_version VARCHAR(32) NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_code (product_code),
  UNIQUE KEY uk_product_neo4j_key (neo4j_node_key),
  KEY idx_product_merchant_status (merchant_id, sale_status, review_status),
  KEY idx_product_brand_status (brand_id, sale_status),
  KEY idx_product_category_status (category_id, sale_status),
  KEY idx_product_name (product_name),
  CONSTRAINT fk_product_merchant FOREIGN KEY (merchant_id) REFERENCES merchant(id) ON DELETE RESTRICT,
  CONSTRAINT fk_product_brand FOREIGN KEY (brand_id) REFERENCES brand(id) ON DELETE RESTRICT,
  CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='食品商品主数据与审核/图谱同步状态';

CREATE TABLE IF NOT EXISTS product_spec (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  spec_code VARCHAR(48) NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  spec_name VARCHAR(160) NOT NULL,
  barcode VARCHAR(64) NULL,
  unit_name VARCHAR(32) NOT NULL DEFAULT '件',
  net_content_value DECIMAL(12,3) NULL,
  net_content_unit VARCHAR(16) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_spec_code (spec_code),
  UNIQUE KEY uk_product_spec_name (product_id, spec_name),
  UNIQUE KEY uk_product_spec_barcode (barcode),
  KEY idx_product_spec_product_status (product_id, status),
  CONSTRAINT fk_product_spec_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='商品可售规格';

CREATE TABLE IF NOT EXISTS product_image (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  spec_id BIGINT UNSIGNED NULL,
  image_type VARCHAR(24) NOT NULL DEFAULT 'MAIN' COMMENT 'MAIN/GALLERY/LABEL/NUTRITION',
  image_url VARCHAR(1024) NOT NULL,
  alt_text VARCHAR(255) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_image_sort (product_id, image_type, sort_order),
  KEY idx_product_image_spec (spec_id),
  CONSTRAINT fk_product_image_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_image_spec FOREIGN KEY (spec_id) REFERENCES product_spec(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='商品图片与标签证据图片';

CREATE TABLE IF NOT EXISTS product_price (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  spec_id BIGINT UNSIGNED NOT NULL,
  price_type VARCHAR(24) NOT NULL DEFAULT 'SALE' COMMENT 'SALE/LIST/PROMOTION',
  amount DECIMAL(12,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'CNY',
  valid_from DATETIME(3) NOT NULL,
  valid_to DATETIME(3) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_price_version (spec_id, price_type, valid_from),
  KEY idx_product_price_active (product_id, spec_id, status, valid_from, valid_to),
  CONSTRAINT fk_product_price_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_price_spec FOREIGN KEY (spec_id) REFERENCES product_spec(id) ON DELETE CASCADE,
  CONSTRAINT chk_product_price_amount CHECK (amount >= 0)
) ENGINE=InnoDB COMMENT='商品价格历史与生效区间';

CREATE TABLE IF NOT EXISTS product_inventory (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  spec_id BIGINT UNSIGNED NOT NULL,
  warehouse_code VARCHAR(32) NOT NULL DEFAULT 'DEFAULT',
  available_qty INT UNSIGNED NOT NULL DEFAULT 0,
  locked_qty INT UNSIGNED NOT NULL DEFAULT 0,
  warning_threshold INT UNSIGNED NOT NULL DEFAULT 10,
  inventory_status VARCHAR(24) NOT NULL DEFAULT 'NORMAL' COMMENT 'NORMAL/LOW/OUT_OF_STOCK/DISABLED',
  version_no BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_inventory_spec_warehouse (spec_id, warehouse_code),
  KEY idx_inventory_product_status (product_id, inventory_status),
  CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
  CONSTRAINT fk_inventory_spec FOREIGN KEY (spec_id) REFERENCES product_spec(id) ON DELETE CASCADE,
  CONSTRAINT chk_inventory_locked CHECK (locked_qty <= available_qty)
) ENGINE=InnoDB COMMENT='可售规格库存';

CREATE TABLE IF NOT EXISTS inventory_change_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  inventory_id BIGINT UNSIGNED NOT NULL,
  business_type VARCHAR(32) NOT NULL COMMENT 'INBOUND/ORDER_LOCK/ORDER_DEDUCT/ORDER_RELEASE/ADJUST',
  business_code VARCHAR(64) NULL,
  quantity_delta INT NOT NULL,
  before_qty INT UNSIGNED NOT NULL,
  after_qty INT UNSIGNED NOT NULL,
  operator_user_id BIGINT UNSIGNED NULL,
  reason VARCHAR(500) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_inventory_log_inventory_time (inventory_id, created_at),
  UNIQUE KEY uk_inventory_log_business_inventory (inventory_id, business_type, business_code),
  KEY idx_inventory_log_business (business_type, business_code),
  CONSTRAINT fk_inventory_log_inventory FOREIGN KEY (inventory_id) REFERENCES product_inventory(id) ON DELETE RESTRICT,
  CONSTRAINT fk_inventory_log_operator FOREIGN KEY (operator_user_id) REFERENCES sys_user(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='库存变更记录';

CREATE TABLE IF NOT EXISTS product_ingredient_snapshot (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  snapshot_code VARCHAR(48) NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  spec_id BIGINT UNSIGNED NULL,
  version_no INT UNSIGNED NOT NULL DEFAULT 1,
  entity_type VARCHAR(16) NOT NULL DEFAULT 'INGREDIENT' COMMENT 'INGREDIENT/ADDITIVE/UNKNOWN',
  entity_code VARCHAR(40) NOT NULL COMMENT 'ingredient_code或additive_code；未知项使用UNK编码',
  normalized_name VARCHAR(160) NOT NULL,
  relation_type VARCHAR(24) NOT NULL COMMENT 'CONTAINS/MAY_CONTAIN/UNKNOWN',
  raw_fragment VARCHAR(500) NULL,
  confidence DECIMAL(5,4) NULL,
  source_code VARCHAR(40) NOT NULL,
  audit_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  graph_sync_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  effective_from DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  effective_to DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_ingredient_snapshot_code (snapshot_code),
  UNIQUE KEY uk_ingredient_snapshot_version (product_id, version_no, entity_code, relation_type),
  KEY idx_ingredient_snapshot_entity (entity_code, relation_type, audit_status),
  KEY idx_ingredient_snapshot_product_active (product_id, effective_to),
  CONSTRAINT fk_ingredient_snapshot_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
  CONSTRAINT fk_ingredient_snapshot_spec FOREIGN KEY (spec_id) REFERENCES product_spec(id) ON DELETE SET NULL,
  CONSTRAINT chk_ingredient_relation CHECK (relation_type IN ('CONTAINS','MAY_CONTAIN','UNKNOWN')),
  CONSTRAINT chk_ingredient_confidence CHECK (confidence IS NULL OR (confidence BETWEEN 0 AND 1))
) ENGINE=InnoDB COMMENT='与原始配料文本分离的结构化配料版本快照';

CREATE TABLE IF NOT EXISTS product_nutrition (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  product_id BIGINT UNSIGNED NOT NULL,
  spec_id BIGINT UNSIGNED NULL,
  nutrient_code VARCHAR(40) NOT NULL,
  nutrient_name VARCHAR(120) NOT NULL,
  nutrient_value DECIMAL(14,4) NULL COMMENT '空值表示暂无数据，禁止伪造',
  unit VARCHAR(24) NOT NULL,
  basis VARCHAR(32) NOT NULL COMMENT 'PER_100G/PER_100ML/PER_SERVING',
  basis_quantity DECIMAL(10,3) NOT NULL DEFAULT 100,
  source_code VARCHAR(40) NOT NULL,
  audit_status VARCHAR(24) NOT NULL DEFAULT 'APPROVED',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_nutrition (product_id, spec_id, nutrient_code, basis),
  KEY idx_nutrition_query (nutrient_code, basis, nutrient_value),
  CONSTRAINT fk_product_nutrition_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_nutrition_spec FOREIGN KEY (spec_id) REFERENCES product_spec(id) ON DELETE SET NULL,
  CONSTRAINT chk_nutrition_value CHECK (nutrient_value IS NULL OR nutrient_value >= 0)
) ENGINE=InnoDB COMMENT='商品营养值，保存数值、单位与基准';

CREATE TABLE IF NOT EXISTS cart (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cart_code VARCHAR(40) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_cart_code (cart_code),
  UNIQUE KEY uk_cart_user_status (user_id, status),
  CONSTRAINT fk_cart_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='用户购物车';

CREATE TABLE IF NOT EXISTS cart_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  cart_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  spec_id BIGINT UNSIGNED NOT NULL,
  quantity INT UNSIGNED NOT NULL DEFAULT 1,
  selected_flag TINYINT(1) NOT NULL DEFAULT 1,
  added_price DECIMAL(12,2) NOT NULL COMMENT '加入购物车时价格，仅供提示，结算需重查',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_cart_item (cart_id, spec_id),
  KEY idx_cart_item_product (product_id),
  CONSTRAINT fk_cart_item_cart FOREIGN KEY (cart_id) REFERENCES cart(id) ON DELETE CASCADE,
  CONSTRAINT fk_cart_item_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE RESTRICT,
  CONSTRAINT fk_cart_item_spec FOREIGN KEY (spec_id) REFERENCES product_spec(id) ON DELETE RESTRICT,
  CONSTRAINT chk_cart_item_quantity CHECK (quantity > 0)
) ENGINE=InnoDB COMMENT='购物车商品项';

CREATE TABLE IF NOT EXISTS favorite (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_favorite_user_product (user_id, product_id),
  KEY idx_favorite_product (product_id),
  CONSTRAINT fk_favorite_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE,
  CONSTRAINT fk_favorite_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='商品收藏';

CREATE TABLE IF NOT EXISTS browsing_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  view_count INT UNSIGNED NOT NULL DEFAULT 1,
  last_viewed_at DATETIME(3) NOT NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_browsing_user_product (user_id, product_id),
  KEY idx_browsing_user_time (user_id, last_viewed_at),
  CONSTRAINT fk_browsing_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE,
  CONSTRAINT fk_browsing_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='用户商品浏览历史';

CREATE TABLE IF NOT EXISTS order_info (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_no VARCHAR(40) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  merchant_id BIGINT UNSIGNED NOT NULL,
  order_status VARCHAR(24) NOT NULL COMMENT 'PENDING_PAYMENT/PENDING_SHIPMENT/SHIPPED/COMPLETED/CANCELLED/REFUND_REQUESTED',
  payment_status VARCHAR(24) NOT NULL DEFAULT 'UNPAID',
  receiver_snapshot JSON NOT NULL COMMENT '收货人、电话与完整地址快照',
  goods_amount DECIMAL(14,2) NOT NULL,
  discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  shipping_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  payable_amount DECIMAL(14,2) NOT NULL,
  paid_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  currency CHAR(3) NOT NULL DEFAULT 'CNY',
  buyer_remark VARCHAR(500) NULL,
  placed_at DATETIME(3) NOT NULL,
  paid_at DATETIME(3) NULL,
  shipped_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  cancelled_at DATETIME(3) NULL,
  cancel_reason VARCHAR(500) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_order_no (order_no),
  KEY idx_order_user_status_time (user_id, order_status, placed_at),
  KEY idx_order_merchant_status_time (merchant_id, order_status, placed_at),
  CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE RESTRICT,
  CONSTRAINT fk_order_merchant FOREIGN KEY (merchant_id) REFERENCES merchant(id) ON DELETE RESTRICT,
  CONSTRAINT chk_order_amounts CHECK (goods_amount >= 0 AND discount_amount >= 0 AND shipping_amount >= 0 AND payable_amount >= 0 AND paid_amount >= 0)
) ENGINE=InnoDB COMMENT='订单主表';

CREATE TABLE IF NOT EXISTS order_item (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  order_item_code VARCHAR(48) NOT NULL,
  product_id BIGINT UNSIGNED NULL,
  spec_id BIGINT UNSIGNED NULL,
  product_code_snapshot VARCHAR(40) NOT NULL,
  product_name_snapshot VARCHAR(200) NOT NULL,
  spec_code_snapshot VARCHAR(48) NOT NULL,
  spec_name_snapshot VARCHAR(160) NOT NULL,
  image_url_snapshot VARCHAR(1024) NULL,
  unit_price DECIMAL(12,2) NOT NULL,
  quantity INT UNSIGNED NOT NULL,
  subtotal_amount DECIMAL(14,2) NOT NULL,
  ingredient_version_snapshot INT UNSIGNED NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_order_item_code (order_item_code),
  KEY idx_order_item_order (order_id),
  KEY idx_order_item_product_code (product_code_snapshot),
  CONSTRAINT fk_order_item_order FOREIGN KEY (order_id) REFERENCES order_info(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_item_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE SET NULL,
  CONSTRAINT fk_order_item_spec FOREIGN KEY (spec_id) REFERENCES product_spec(id) ON DELETE SET NULL,
  CONSTRAINT chk_order_item_quantity CHECK (quantity > 0),
  CONSTRAINT chk_order_item_amount CHECK (unit_price >= 0 AND subtotal_amount >= 0)
) ENGINE=InnoDB COMMENT='订单商品与价格/名称/规格快照';

CREATE TABLE IF NOT EXISTS payment_record (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  payment_no VARCHAR(48) NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  payment_channel VARCHAR(32) NOT NULL COMMENT 'MOCK_BALANCE/MOCK_ALIPAY/MOCK_WECHAT',
  payment_status VARCHAR(24) NOT NULL COMMENT 'PENDING/SUCCESS/FAILED/REFUNDED',
  amount DECIMAL(14,2) NOT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'CNY',
  provider_transaction_no VARCHAR(80) NULL,
  failure_code VARCHAR(64) NULL,
  failure_message VARCHAR(500) NULL,
  requested_at DATETIME(3) NOT NULL,
  completed_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_payment_no (payment_no),
  UNIQUE KEY uk_payment_provider_tx (provider_transaction_no),
  KEY idx_payment_order_status (order_id, payment_status),
  CONSTRAINT fk_payment_order FOREIGN KEY (order_id) REFERENCES order_info(id) ON DELETE RESTRICT,
  CONSTRAINT chk_payment_amount CHECK (amount >= 0)
) ENGINE=InnoDB COMMENT='模拟或真实支付渠道记录';

CREATE TABLE IF NOT EXISTS product_review (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  review_code VARCHAR(40) NOT NULL,
  order_item_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  rating TINYINT UNSIGNED NOT NULL,
  review_text VARCHAR(2000) NULL,
  ingredient_correction_text VARCHAR(1000) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'PUBLISHED',
  reviewed_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_review_code (review_code),
  UNIQUE KEY uk_product_review_order_item (order_item_id),
  KEY idx_product_review_product_status (product_id, status, reviewed_at),
  KEY idx_product_review_user (user_id, reviewed_at),
  CONSTRAINT fk_product_review_order_item FOREIGN KEY (order_item_id) REFERENCES order_item(id) ON DELETE SET NULL,
  CONSTRAINT fk_product_review_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE RESTRICT,
  CONSTRAINT fk_product_review_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
  CONSTRAINT chk_product_review_rating CHECK (rating BETWEEN 1 AND 5)
) ENGINE=InnoDB COMMENT='商品评价与成分纠错建议';

CREATE TABLE IF NOT EXISTS product_audit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  audit_code VARCHAR(40) NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  product_version INT UNSIGNED NOT NULL DEFAULT 1,
  audit_stage VARCHAR(32) NOT NULL COMMENT 'FIELD_CHECK/AI_NORMALIZE/KNOWLEDGE_REVIEW/MANUAL_REVIEW',
  audit_status VARCHAR(24) NOT NULL COMMENT 'PENDING/APPROVED/REJECTED/NEED_MORE_INFO/TRANSFERRED',
  normalized_result JSON NULL,
  conflict_result JSON NULL,
  audit_opinion VARCHAR(1000) NULL,
  auditor_user_id BIGINT UNSIGNED NULL,
  submitted_by BIGINT UNSIGNED NOT NULL,
  submitted_at DATETIME(3) NOT NULL,
  audited_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_audit_code (audit_code),
  KEY idx_product_audit_product_version (product_id, product_version, created_at),
  KEY idx_product_audit_status (audit_status, submitted_at),
  CONSTRAINT fk_product_audit_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
  CONSTRAINT fk_product_audit_auditor FOREIGN KEY (auditor_user_id) REFERENCES sys_user(id) ON DELETE SET NULL,
  CONSTRAINT fk_product_audit_submitter FOREIGN KEY (submitted_by) REFERENCES sys_user(id) ON DELETE RESTRICT
) ENGINE=InnoDB COMMENT='商品审核历史，永不覆盖旧记录';

CREATE TABLE IF NOT EXISTS anomaly_record (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  anomaly_code VARCHAR(40) NOT NULL,
  anomaly_type VARCHAR(40) NOT NULL COMMENT 'INGREDIENT_MISSING/UNKNOWN_INGREDIENT/ALIAS_UNMAPPED/GRAPH_CONFLICT/NUTRITION_UNIT/MODEL_FAILURE/TIMEOUT',
  target_type VARCHAR(32) NOT NULL,
  target_code VARCHAR(64) NOT NULL,
  title VARCHAR(200) NOT NULL,
  detail_text VARCHAR(2000) NOT NULL,
  severity VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
  process_status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
  assignee_user_id BIGINT UNSIGNED NULL,
  detected_at DATETIME(3) NOT NULL,
  resolved_at DATETIME(3) NULL,
  resolution_text VARCHAR(1000) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_anomaly_code (anomaly_code),
  KEY idx_anomaly_type_status (anomaly_type, process_status, severity),
  KEY idx_anomaly_target (target_type, target_code),
  CONSTRAINT fk_anomaly_assignee FOREIGN KEY (assignee_user_id) REFERENCES sys_user(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='异常数据中心记录';

CREATE TABLE IF NOT EXISTS feedback_ticket (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ticket_code VARCHAR(40) NOT NULL,
  reporter_user_id BIGINT UNSIGNED NOT NULL,
  ticket_type VARCHAR(32) NOT NULL COMMENT 'FILTER_FEEDBACK/INGREDIENT_CORRECTION/COMPLAINT/AFTER_SALES',
  target_type VARCHAR(32) NOT NULL,
  target_code VARCHAR(64) NOT NULL,
  feedback_text VARCHAR(2000) NOT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
  priority VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
  assignee_user_id BIGINT UNSIGNED NULL,
  resolution_text VARCHAR(2000) NULL,
  resolved_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_feedback_ticket_code (ticket_code),
  KEY idx_feedback_status_priority (status, priority, created_at),
  KEY idx_feedback_reporter (reporter_user_id, created_at),
  CONSTRAINT fk_feedback_reporter FOREIGN KEY (reporter_user_id) REFERENCES sys_user(id) ON DELETE RESTRICT,
  CONSTRAINT fk_feedback_assignee FOREIGN KEY (assignee_user_id) REFERENCES sys_user(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='用户反馈与处理闭环';

CREATE TABLE IF NOT EXISTS ai_conversation (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  conversation_code VARCHAR(48) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  conversation_type VARCHAR(32) NOT NULL DEFAULT 'SMART_FILTER',
  context_summary TEXT NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
  expires_at DATETIME(3) NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_conversation_code (conversation_code),
  KEY idx_ai_conversation_user_time (user_id, created_at),
  CONSTRAINT fk_ai_conversation_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='受控AI会话元数据';

CREATE TABLE IF NOT EXISTS ai_filter_history (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  filter_code VARCHAR(48) NOT NULL,
  conversation_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  raw_query TEXT NOT NULL,
  parsed_conditions JSON NOT NULL,
  hard_constraints JSON NOT NULL,
  soft_preferences JSON NOT NULL,
  pending_confirmations JSON NULL,
  result_count INT UNSIGNED NOT NULL DEFAULT 0,
  execution_mode VARCHAR(24) NOT NULL DEFAULT 'AI_GRAPH' COMMENT 'AI_GRAPH/BASIC_FORM/KEYWORD',
  parse_status VARCHAR(24) NOT NULL DEFAULT 'SUCCESS',
  rule_result_summary JSON NULL,
  is_deleted TINYINT(1) NOT NULL DEFAULT 0,
  deleted_at DATETIME(3) NULL,
  executed_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_filter_code (filter_code),
  KEY idx_ai_filter_user_time (user_id, executed_at),
  KEY idx_ai_filter_mode_status (execution_mode, parse_status),
  CONSTRAINT fk_ai_filter_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversation(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_filter_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE
) ENGINE=InnoDB COMMENT='AI筛选原始查询、结构化条件与确定性规则摘要';

CREATE TABLE IF NOT EXISTS ai_model_call_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  call_code VARCHAR(48) NOT NULL,
  conversation_id BIGINT UNSIGNED NULL,
  filter_history_id BIGINT UNSIGNED NULL,
  user_id BIGINT UNSIGNED NULL,
  model_provider VARCHAR(32) NOT NULL DEFAULT 'QWEN',
  model_name VARCHAR(80) NOT NULL,
  request_type VARCHAR(32) NOT NULL,
  prompt_template_version VARCHAR(32) NOT NULL,
  request_hash CHAR(64) NOT NULL COMMENT '不记录不必要的敏感原文',
  response_status VARCHAR(24) NOT NULL,
  validation_status VARCHAR(24) NOT NULL,
  latency_ms INT UNSIGNED NULL,
  input_tokens INT UNSIGNED NULL,
  output_tokens INT UNSIGNED NULL,
  error_code VARCHAR(64) NULL,
  error_message VARCHAR(1000) NULL,
  called_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_model_call_code (call_code),
  KEY idx_ai_model_call_status_time (response_status, called_at),
  KEY idx_ai_model_call_user (user_id, called_at),
  CONSTRAINT fk_ai_call_conversation FOREIGN KEY (conversation_id) REFERENCES ai_conversation(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_call_filter FOREIGN KEY (filter_history_id) REFERENCES ai_filter_history(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_call_user FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='模型调用可观测性与输出校验日志';

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  audit_log_code VARCHAR(48) NOT NULL,
  operator_user_id BIGINT UNSIGNED NULL,
  operator_name_snapshot VARCHAR(120) NOT NULL,
  operation_type VARCHAR(64) NOT NULL,
  object_type VARCHAR(48) NOT NULL,
  object_code VARCHAR(80) NOT NULL,
  before_value JSON NULL,
  after_value JSON NULL,
  reason VARCHAR(1000) NOT NULL,
  request_id VARCHAR(64) NULL,
  client_ip VARCHAR(64) NULL,
  operated_at DATETIME(3) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_audit_log_code (audit_log_code),
  KEY idx_audit_operator_time (operator_user_id, operated_at),
  KEY idx_audit_object (object_type, object_code, operated_at),
  KEY idx_audit_operation_time (operation_type, operated_at),
  CONSTRAINT fk_audit_operator FOREIGN KEY (operator_user_id) REFERENCES sys_user(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='跨审核、图谱、权限与配置的不可变审计记录';

CREATE TABLE IF NOT EXISTS workflow_task (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  task_code VARCHAR(48) NOT NULL,
  workflow_type VARCHAR(40) NOT NULL COMMENT 'PRODUCT_AUDIT/ANOMALY/KNOWLEDGE_REVIEW/FEEDBACK/RECHECK',
  workflow_instance_code VARCHAR(64) NOT NULL,
  business_type VARCHAR(32) NOT NULL,
  business_code VARCHAR(64) NOT NULL,
  node_code VARCHAR(64) NOT NULL,
  node_name VARCHAR(120) NOT NULL,
  task_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  assignee_user_id BIGINT UNSIGNED NULL,
  candidate_role_code VARCHAR(40) NULL,
  payload_json JSON NULL,
  due_at DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  result_json JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_workflow_task_code (task_code),
  KEY idx_workflow_status_due (task_status, due_at),
  KEY idx_workflow_business (business_type, business_code),
  KEY idx_workflow_assignee (assignee_user_id, task_status),
  CONSTRAINT fk_workflow_assignee FOREIGN KEY (assignee_user_id) REFERENCES sys_user(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='低代码工作流人工任务与回写结果';

CREATE TABLE IF NOT EXISTS knowledge_audit (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  knowledge_audit_code VARCHAR(48) NOT NULL,
  graph_version VARCHAR(32) NOT NULL,
  entity_type VARCHAR(32) NOT NULL,
  entity_code VARCHAR(64) NOT NULL,
  change_type VARCHAR(32) NOT NULL COMMENT 'CREATE/UPDATE/MERGE/DISABLE/RELATION_CHANGE/ROLLBACK',
  before_value JSON NULL,
  after_value JSON NULL,
  source_code VARCHAR(40) NOT NULL,
  audit_status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
  submitted_by BIGINT UNSIGNED NOT NULL,
  audited_by BIGINT UNSIGNED NULL,
  audit_opinion VARCHAR(1000) NULL,
  submitted_at DATETIME(3) NOT NULL,
  audited_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_knowledge_audit_code (knowledge_audit_code),
  KEY idx_knowledge_entity_version (entity_type, entity_code, graph_version),
  KEY idx_knowledge_audit_status (audit_status, submitted_at),
  CONSTRAINT fk_knowledge_submitter FOREIGN KEY (submitted_by) REFERENCES sys_user(id) ON DELETE RESTRICT,
  CONSTRAINT fk_knowledge_auditor FOREIGN KEY (audited_by) REFERENCES sys_user(id) ON DELETE SET NULL
) ENGINE=InnoDB COMMENT='知识图谱实体与关系审核历史';
