import { Edit3, Package, PackageCheck, Plus, RefreshCw, ShoppingBag, Store, Truck } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { EmptyState, LoadingBlock, Modal } from '../../components/common/UI'
import { SafeImage } from '../../components/common/SafeImage'
import { useApp } from '../../store/AppStore'
import {
  createMerchantProduct, getCatalogBrands, getCatalogCategories, getMerchantDashboard,
  getMerchantOrders, getMerchantProducts, updateMerchantOrderStatus, updateMerchantProduct,
  updateMerchantProductSale, type CatalogOption, type MerchantDashboardData,
  type MerchantOrder, type MerchantProduct, type ProductWrite,
} from '../../services/workspace'

const emptyProduct:ProductWrite={name:'',subtitle:null,description:null,brand_code:'',category_code:'',raw_ingredient_text:'',allergen_notice:null,spec_name:'',unit_name:'件',price:'0',stock_quantity:0,image_url:null}
const orderLabels:Record<string,string>={PENDING_PAYMENT:'待付款',PAID:'已支付',SHIPPING:'配送中',COMPLETED:'已完成',CANCELLED:'已取消',REFUND_REQUESTED:'退款申请中'}
const reviewLabels:Record<string,string>={DRAFT:'草稿',PENDING:'待审核',APPROVED:'已通过',REJECTED:'已驳回',NEED_MORE_INFO:'需补充'}
const saleLabels:Record<string,string>={DRAFT:'草稿',ON_SALE:'已上架',OFF_SALE:'已下架',SUSPENDED:'已暂停'}

function ErrorBlock({message,retry}:{message:string;retry:()=>void}){return <div className="card"><EmptyState title="数据加载失败" text={message} action={<button className="btn primary" onClick={retry}><RefreshCw/>重新加载</button>}/></div>}

export function MerchantDashboard(){
 const [data,setData]=useState<MerchantDashboardData|null>(null);const [error,setError]=useState('')
 const load=()=>{setError('');void getMerchantDashboard().then(setData).catch(e=>setError(e instanceof Error?e.message:'加载失败'))}
 useEffect(load,[])
 if(error)return <ErrorBlock message={error} retry={load}/>
 if(!data)return <LoadingBlock text="正在读取商家经营数据…"/>
 const metrics=[[Package,'商品总数',data.product_count],[PackageCheck,'已上架',data.on_sale_count],[ShoppingBag,'订单总数',data.order_count],[Truck,'有效订单',data.paid_order_count],[Store,'累计销售额',`¥${data.sales_amount}`]] as const
 return <><div className="dashboard-head"><div><span className="eyebrow">MERCHANT DASHBOARD</span><h1>{data.merchant_name}</h1><p>以下数据仅统计当前登录商家。</p></div></div><div className="dashboard-grid">{metrics.map(([Icon,label,value])=><div className="metric-card card" key={label}><div className="metric-top"><span>{label}</span><span className="metric-icon"><Icon/></span></div><strong>{value}</strong><p>{label==='商品总数'?`${data.pending_review_count} 件待审核`:'来自 MySQL 实时统计'}</p></div>)}</div></>
}

function ProductForm({open,product,onClose,onSaved}:{open:boolean;product:MerchantProduct|null;onClose:()=>void;onSaved:()=>void}){
 const {notify}=useApp();const [form,setForm]=useState<ProductWrite>(emptyProduct);const [categories,setCategories]=useState<CatalogOption[]>([]);const [brands,setBrands]=useState<CatalogOption[]>([]);const [saving,setSaving]=useState(false)
 useEffect(()=>{if(!open)return;void Promise.all([getCatalogCategories(),getCatalogBrands()]).then(([c,b])=>{setCategories(c);setBrands(b)});setForm(product?{name:product.name,subtitle:product.subtitle,description:product.description,brand_code:product.brand_code,category_code:product.category_code,raw_ingredient_text:product.raw_ingredient_text,allergen_notice:product.allergen_notice,spec_name:product.spec_name,unit_name:product.unit_name,price:product.sale_price||'0',stock_quantity:product.stock_quantity||0,image_url:product.image_url}:emptyProduct)},[open,product])
 const set=<K extends keyof ProductWrite>(key:K,value:ProductWrite[K])=>setForm(v=>({...v,[key]:value}))
 const submit=async(e:FormEvent)=>{e.preventDefault();setSaving(true);try{if(product)await updateMerchantProduct(product.product_code,form);else await createMerchantProduct(form);notify(product?'商品已更新并重新进入审核':'商品已创建并提交审核');onSaved();onClose()}catch(err){notify(err instanceof Error?err.message:'保存失败','error')}finally{setSaving(false)}}
 return <Modal open={open} title={product?'编辑商品':'新增商品'} onClose={onClose}><form onSubmit={submit}><div className="form-grid"><div className="field span-2"><label>商品名称</label><input className="input" required value={form.name} onChange={e=>set('name',e.target.value)}/></div><div className="field"><label>品牌</label><select className="select" required value={form.brand_code} onChange={e=>set('brand_code',e.target.value)}><option value="">请选择</option>{brands.map(x=><option key={x.brand_code} value={x.brand_code}>{x.name}</option>)}</select></div><div className="field"><label>分类</label><select className="select" required value={form.category_code} onChange={e=>set('category_code',e.target.value)}><option value="">请选择</option>{categories.map(x=><option key={x.category_code} value={x.category_code}>{x.name}</option>)}</select></div><div className="field"><label>规格</label><input className="input" required value={form.spec_name} onChange={e=>set('spec_name',e.target.value)}/></div><div className="field"><label>单位</label><input className="input" required value={form.unit_name} onChange={e=>set('unit_name',e.target.value)}/></div><div className="field"><label>价格</label><input className="input" min="0" step="0.01" type="number" required value={form.price} onChange={e=>set('price',e.target.value)}/></div><div className="field"><label>库存</label><input className="input" min="0" type="number" required value={form.stock_quantity} onChange={e=>set('stock_quantity',Number(e.target.value))}/></div><div className="field span-2"><label>原始配料表</label><textarea className="textarea" required value={form.raw_ingredient_text} onChange={e=>set('raw_ingredient_text',e.target.value)}/></div><div className="field span-2"><label>过敏原提示</label><input className="input" value={form.allergen_notice||''} onChange={e=>set('allergen_notice',e.target.value||null)}/></div><div className="field span-2"><label>主图 URL</label><input className="input" value={form.image_url||''} onChange={e=>set('image_url',e.target.value||null)}/></div></div><div className="modal-footer"><button type="button" className="btn ghost" onClick={onClose}>取消</button><button className="btn primary" disabled={saving}>{saving?'保存中…':'保存并提交审核'}</button></div></form></Modal>
}

export function MerchantProducts(){
 const {notify}=useApp();const [items,setItems]=useState<MerchantProduct[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [editing,setEditing]=useState<MerchantProduct|null>(null);const [formOpen,setFormOpen]=useState(false)
 const load=()=>{setLoading(true);setError('');void getMerchantProducts().then(setItems).catch(e=>setError(e instanceof Error?e.message:'加载失败')).finally(()=>setLoading(false))};useEffect(load,[])
 const sale=async(item:MerchantProduct)=>{const target=item.sale_status==='ON_SALE'?'OFF_SALE':'ON_SALE';try{await updateMerchantProductSale(item.product_code,target);notify(target==='ON_SALE'?'商品已上架':'商品已下架');load()}catch(e){notify(e instanceof Error?e.message:'操作失败','error')}}
 return <><div className="dashboard-head"><div><h1>商品管理</h1><p>商品范围由当前 JWT 对应商家自动限定。</p></div><button className="btn primary" onClick={()=>{setEditing(null);setFormOpen(true)}}><Plus/>新增商品</button></div>{loading?<LoadingBlock/>:error?<ErrorBlock message={error} retry={load}/>:items.length===0?<EmptyState title="暂无商品" text="可创建第一件待审核商品"/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>商品</th><th>品牌 / 分类</th><th>价格</th><th>库存</th><th>审核</th><th>状态</th><th>操作</th></tr></thead><tbody>{items.map(item=><tr key={item.product_code}><td><div className="table-product"><SafeImage src={item.image_url||undefined}/><span><b>{item.name}</b><small style={{display:'block'}}>{item.product_code}</small></span></div></td><td>{item.brand}<br/><small>{item.category}</small></td><td>{item.sale_price===null?'暂无价格':`¥${item.sale_price}`}</td><td>{item.stock_quantity??'暂无'}</td><td><span className={`status-pill ${item.review_status==='APPROVED'?'success':item.review_status==='REJECTED'?'danger':'warn'}`}>{reviewLabels[item.review_status]||item.review_status}</span></td><td>{saleLabels[item.sale_status]||item.sale_status}</td><td><button className="icon-btn" title="编辑" onClick={()=>{setEditing(item);setFormOpen(true)}}><Edit3 size={16}/></button><button className="btn ghost" onClick={()=>void sale(item)}>{item.sale_status==='ON_SALE'?'下架':'上架'}</button></td></tr>)}</tbody></table></div>}<ProductForm open={formOpen} product={editing} onClose={()=>setFormOpen(false)} onSaved={load}/></>
}

export function MerchantOrders(){
 const {notify}=useApp();const [items,setItems]=useState<MerchantOrder[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 const load=()=>{setLoading(true);setError('');void getMerchantOrders().then(setItems).catch(e=>setError(e instanceof Error?e.message:'加载失败')).finally(()=>setLoading(false))};useEffect(load,[])
 const advance=async(order:MerchantOrder)=>{const target=order.status==='PAID'?'SHIPPING':'COMPLETED';try{await updateMerchantOrderStatus(order.id,target);notify(target==='SHIPPING'?'订单已开始配送':'订单已完成');load()}catch(e){notify(e instanceof Error?e.message:'状态更新失败','error')}}
 return <><div className="dashboard-head"><div><h1>订单管理</h1><p>仅展示购买当前商家商品的订单。</p></div></div>{loading?<LoadingBlock/>:error?<ErrorBlock message={error} retry={load}/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>订单号</th><th>买家</th><th>商品数</th><th>金额</th><th>状态</th><th>下单时间</th><th>操作</th></tr></thead><tbody>{items.map(order=><tr key={order.id}><td>{order.order_no}</td><td>{order.buyer}</td><td>{order.item_count}</td><td>¥{order.payable_amount}</td><td><span className="status-pill">{orderLabels[order.status]||order.status}</span></td><td>{new Date(order.placed_at).toLocaleString('zh-CN')}</td><td>{(order.status==='PAID'||order.status==='SHIPPING')?<button className="btn primary" onClick={()=>void advance(order)}>{order.status==='PAID'?'开始配送':'完成订单'}</button>:<span className="muted">无可用操作</span>}</td></tr>)}</tbody></table></div>}</>
}