import { Check, Eye, Package, Power, RefreshCw, Search, ShoppingBag, Store, Users } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { EmptyState, LoadingBlock, Modal } from '../../components/common/UI'
import { useApp } from '../../store/AppStore'
import { approveAdminProduct, getAdminDashboard, getAdminProducts, getAdminUsers, updateAdminUserStatus, type AdminDashboardData, type AdminProduct, type AdminUser } from '../../services/workspace'

const roleLabels:Record<string,string>={CONSUMER:'消费者',MERCHANT:'商家',ADMIN:'平台管理员',PLATFORM_ADMIN:'平台管理员',KNOWLEDGE_ADMIN:'知识管理员',OPS:'运维'}
const statusLabels:Record<string,string>={ACTIVE:'正常',FROZEN:'冻结',PENDING:'待审核',DISABLED:'停用',DRAFT:'草稿',APPROVED:'已通过',REJECTED:'已驳回',NEED_MORE_INFO:'需补充',ON_SALE:'已上架',OFF_SALE:'已下架'}
function ErrorBlock({message,retry}:{message:string;retry:()=>void}){return <div className="card"><EmptyState title="数据加载失败" text={message} action={<button className="btn primary" onClick={retry}><RefreshCw/>重新加载</button>}/></div>}

export function AdminDashboard(){
 const [data,setData]=useState<AdminDashboardData|null>(null);const [error,setError]=useState('');const load=()=>{setError('');void getAdminDashboard().then(setData).catch(e=>setError(e instanceof Error?e.message:'加载失败'))};useEffect(load,[])
 if(error)return <ErrorBlock message={error} retry={load}/>;if(!data)return <LoadingBlock text="正在读取平台统计…"/>
 const metrics=[[Users,'用户数',data.user_count],[Store,'商家数',data.merchant_count],[Package,'商品数',data.product_count],[ShoppingBag,'订单数',data.order_count]] as const
 return <><div className="dashboard-head"><div><span className="eyebrow">ADMIN DASHBOARD</span><h1>平台统计</h1><p>指标来自 MySQL 当前业务数据。</p></div></div><div className="dashboard-grid">{metrics.map(([Icon,label,value])=><div className="metric-card card" key={label}><div className="metric-top"><span>{label}</span><span className="metric-icon"><Icon/></span></div><strong>{value}</strong><p>{label==='商品数'?`${data.pending_product_count} 件待审核`:'实时统计'}</p></div>)}</div></>
}

export function UserManagement(){
 const {notify}=useApp();const [items,setItems]=useState<AdminUser[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [keyword,setKeyword]=useState('');const [selected,setSelected]=useState<AdminUser|null>(null);const [updatingId,setUpdatingId]=useState<number|null>(null)
 const load=(search=keyword)=>{setLoading(true);setError('');void getAdminUsers(search.trim()).then(setItems).catch(e=>setError(e instanceof Error?e.message:'加载失败')).finally(()=>setLoading(false))};useEffect(()=>load(''),[])
 const search=(event:FormEvent)=>{event.preventDefault();load(keyword)}
 const toggleStatus=async(user:AdminUser)=>{const target=user.status==='ACTIVE'?'DISABLED':'ACTIVE';if(!window.confirm(`确认${target==='DISABLED'?'禁用':'启用'}用户 ${user.username}？`))return;setUpdatingId(user.id);try{await updateAdminUserStatus(user.id,target);notify(target==='DISABLED'?'用户已禁用':'用户已启用');setSelected(current=>current?.id===user.id?{...current,status:target}:current);load(keyword)}catch(e){notify(e instanceof Error?e.message:'状态更新失败','error')}finally{setUpdatingId(null)}}
 return <><div className="dashboard-head"><div><h1>用户管理</h1><p>用户账号、角色和状态均来自系统用户表。</p></div><form className="workspace-search" onSubmit={search}><Search/><input value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="搜索用户名或邮箱"/><button className="btn primary" type="submit">搜索</button></form></div>{loading?<LoadingBlock/>:error?<ErrorBlock message={error} retry={()=>load(keyword)}/>:items.length===0?<EmptyState title="未找到用户" text="请调整用户名或邮箱关键词"/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>用户编码</th><th>用户名</th><th>邮箱</th><th>角色</th><th>状态</th><th>注册时间</th><th>操作</th></tr></thead><tbody>{items.map(user=><tr key={user.id}><td>{user.user_code}</td><td>{user.username}</td><td>{user.email||'暂无'}</td><td>{user.roles.map(role=>roleLabels[role]||role).join('、')}</td><td><span className={`status-pill ${user.status==='ACTIVE'?'success':'warn'}`}>{statusLabels[user.status]||user.status}</span></td><td>{new Date(user.created_at).toLocaleString('zh-CN')}</td><td><button className="icon-btn" title="查看详情" onClick={()=>setSelected(user)}><Eye size={16}/></button>{(user.status==='ACTIVE'||user.status==='DISABLED')&&<button className={`btn ${user.status==='ACTIVE'?'danger':'primary'}`} disabled={updatingId===user.id} onClick={()=>void toggleStatus(user)}><Power size={15}/>{user.status==='ACTIVE'?'禁用':'启用'}</button>}</td></tr>)}</tbody></table></div>}<Modal open={!!selected} title="用户详情" onClose={()=>setSelected(null)}><div className="form-grid"><div className="field"><label>用户编码</label><input className="input" readOnly value={selected?.user_code||''}/></div><div className="field"><label>用户名</label><input className="input" readOnly value={selected?.username||''}/></div><div className="field"><label>邮箱</label><input className="input" readOnly value={selected?.email||'暂无'}/></div><div className="field"><label>角色</label><input className="input" readOnly value={selected?.roles.map(role=>roleLabels[role]||role).join('、')||''}/></div><div className="field"><label>状态</label><input className="input" readOnly value={selected?statusLabels[selected.status]||selected.status:''}/></div><div className="field"><label>注册时间</label><input className="input" readOnly value={selected?new Date(selected.created_at).toLocaleString('zh-CN'):''}/></div></div></Modal></>
}

export function ProductReview(){
 const {notify}=useApp();const [items,setItems]=useState<AdminProduct[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [selected,setSelected]=useState<AdminProduct|null>(null);const [opinion,setOpinion]=useState('');const [saving,setSaving]=useState(false)
 const load=()=>{setLoading(true);setError('');void getAdminProducts('PENDING').then(setItems).catch(e=>setError(e instanceof Error?e.message:'加载失败')).finally(()=>setLoading(false))};useEffect(load,[])
 const approve=async()=>{if(!selected)return;setSaving(true);try{await approveAdminProduct(selected.product_code,opinion);notify('商品审核已通过');setSelected(null);setOpinion('');load()}catch(e){notify(e instanceof Error?e.message:'审核失败','error')}finally{setSaving(false)}}
 return <><div className="dashboard-head"><div><h1>商品审核</h1><p>仅显示 MySQL 中待审核商品。</p></div></div>{loading?<LoadingBlock/>:error?<ErrorBlock message={error} retry={load}/>:items.length===0?<EmptyState title="暂无待审核商品" text="当前审核队列为空"/>:<div className="table-wrap"><table className="data-table"><thead><tr><th>商品</th><th>商家</th><th>品牌</th><th>分类</th><th>状态</th><th>提交时间</th><th>操作</th></tr></thead><tbody>{items.map(item=><tr key={item.product_code}><td><b>{item.name}</b><small style={{display:'block'}}>{item.product_code}</small></td><td>{item.merchant_name}<small style={{display:'block'}}>{item.merchant_code}</small></td><td>{item.brand}</td><td>{item.category}</td><td><span className="status-pill warn">{statusLabels[item.review_status]||item.review_status}</span></td><td>{item.submitted_at?new Date(item.submitted_at).toLocaleString('zh-CN'):'暂无'}</td><td><button className="btn primary" onClick={()=>setSelected(item)}><Check/>审核通过</button></td></tr>)}</tbody></table></div>}<Modal open={!!selected} title="确认审核通过" onClose={()=>setSelected(null)} footer={<><button className="btn ghost" onClick={()=>setSelected(null)}>取消</button><button className="btn primary" disabled={saving} onClick={()=>void approve()}>{saving?'处理中…':'确认通过'}</button></>}><p>商品：{selected?.name}</p><div className="field"><label>审核意见</label><textarea className="textarea" value={opinion} onChange={e=>setOpinion(e.target.value)} placeholder="可填写审核依据"/></div></Modal></>
}